Lightning-AI/litgpt

- .github/workflows/cpu-tests.yml
- generate.py
- lit_stablelm/__init__.py
- lit_stablelm/model.py
- requirements.txt
- setup.py
- tests/test_model.py
> Install torch nightly for flash attention

- chat.py
- generate.py
- lit_stablelm/utils.py
- scripts/convert_hf_checkpoint.py
- tests/test_generate.py
- tests/test_utils.py
Fixes https://github.com/Lightning-AI/lit-stablelm/issues/9
Example message:
```bash
$ python generate.py --checkpoint_dir dir/that/doesnt/exist
File "/home/carmocca/git/lit-stablelm/generate.py", line 153, in <module>
CLI(main)
File "/home/carmocca/git/nightly-venv/lib/python3.10/site-packages/jsonargparse/cli.py", line 82, in CLI
return _run_component(component, cfg_init)
File "/home/carmocca/git/nightly-venv/lib/python3.10/site-packages/jsonargparse/cli.py", line 147, in _run_component
return component(**cfg)
File "/home/carmocca/git/lit-stablelm/generate.py", line 98, in main
check_valid_checkpoint_dir(checkpoint_dir)
File "/home/carmocca/git/lit-stablelm/lit_stablelm/utils.py", line 294, in check_valid_checkpoint_dir
raise OSError(message)
OSError: …
```
> Better UX for discovering checkpoints

- scripts/convert_hf_checkpoint.py
Closes https://github.com/Lightning-AI/lit-llama/pull/250
This check is misplaced, as this is the function that is meant to save the weights.
> Remove checkpoint_dir check when converting weights

- chat.py
Currently, there is no spacing between the reply output and the `Time for inference: ...` output. Added a print statement to separate the two.
> Cleanup reply output in chat.py

- lit_parrot/model.py
Right now the cache defaulted to the `default_tensor_dtype`, here we set it to the type of the input of `block`.
> Set dtype of kv_caches correctly

- lit_parrot/config.py
Currently, converting the HF checkpoints for pythia-6.9b and pythia-12b does not work due to a dimension mismatch. Upon further examination this is because the `vocab_size` was not specified in `config.py`. This PR should fix this issue.
> Adding `vocab_size` to `config.py`

- lit_parrot/adapter.py
This PR adds caching for `ak` and `av` (adapter keys and adapter values, respectively).
Based on #51 & #58
> Adding caching for adapter KVs

- howto/tpus.md
This minor documentation change is needed because lit parrot requires torch newer than 2.0.0. Once there is a newer version available when creating cloud TPUs, we can remove these installations.
> Updated TPU docs to download nightly torch dependencies

- lit_parrot/adapter.py
- lit_parrot/model.py
On `xla` devices, we want to also reset `rope_cache` and `mask_cache` in `reset_cache()`. Rational is explained in https://github.com/Lightning-AI/lit-parrot/pull/83#issuecomment-1558150179
> Reset all caches on xla devices

- lit_parrot/adapter.py
Changes
- Reorder model top to bottom to match the non-adapter structure
- Have `CausalSelfAttention` subclass `BaseCausalSelfAttention` to reuse part of the `__init__`
> Reorder adapter and subclass CausalSelfAttention

- finetune_adapter.py
- generate.py
- train_redpajama.py
Changes:
- Fix max_iters to account for the `micro_batch_size`, as the `epoch_size` is defined as the length of the dataset, not the length of the dataloader
The same issues exist in Lit-LlaMA.
> Fix max_iters logic

- finetune_adapter.py
To make the finetuning work on mac Metal Performance Shaders (MPS) accelerators with custom command line arguments such as:
```
python finetune_adapter.py --checkpoint_dir checkpoints/stabilityai/stablelm-base-alpha-3b --accelerator mps --precision 32-true --dtype float32
```
> Be able to set custom accelerator, precision and dtype for MPS accelerators (Apple M1 silicon)

- howto/download_falcon.md
This is a small bugfix, looks like generate.py was renamed.
> Fix to point to correct generation script in Falcon documentation

- finetune/adapter.py
- finetune/adapter_v2.py
- Previously, it was not possible to use the scripts with multi-GPU training because deepspeed doesn't support "bf16-true", and "32-true" is too expensive. This modification now allows "bf16-mixed" as a precision argument. 
- Furthermore, it also uses `fabric.print` to prevent duplicated lines when using multiple GPUs.
> Fix adapter scripts for multi-gpu training

- quantize/gptq.py
- requirements.txt
Fixes the `datasets` requirements issue mentioned in #113 .
I also moved the import from the `get_sample_data()` up to the top, because `get_sample_data()` gets called in `main`, which a user would always encounter, if I understand correctly.
(Correct me if I'm wrong @carmocca and the `get_sample_data()` was a temporary debugging thing that should not be there?)
> Add datasets to requirements

- finetune/adapter.py
- finetune/adapter_v2.py
- scripts/convert_hf_checkpoint.py
- scripts/download.py
- scripts/prepare_alpaca.py
- scripts/prepare_redpajama.py
This PR attempts to fix https://github.com/Lightning-AI/lit-parrot/issues/122 by making `max_seq_length` an optional parameter in `scripts/prepare_alpaca.py`, 'finetune/adapter.py` and 'finetune/adapter_v2.py`. 
Currently, all of these scripts use `max_seq_length=256`, which I suspect truncates inputs to the models. There is also an annoying manual dependency between changing this value in one script and then having to make the others match. Instead, this PR uses the `block_size` of the checkpointed model as a default value for `max_seq_length` which can still be manually overridden from the commandline. 
I also changed a few places where functions in `prepare_alpaca.py` had contradictory or confusing default values for arguments and instead expose all the defaults as top-level defined …
> Set the config's block size  as the max_seq_length data preparation and fine tuning scripts

- finetune/adapter.py
- finetune/adapter_v2.py
This PR adds changes specific for finetuning on TPUs. 
Used TPU v4-8 with
```
log_interval = 1
devices = 4
batch_size = 64 / devices
micro_batch_size = 4
gradient_accumulation_steps = 4
num_epochs = 5
```
for stablelm-base-alpha-3b; resulting finetuning time ~= 4500s.
> [TPU] XLA changes for finetuning

- finetune/adapter_v2.py
In one place it had the regular `"out/adapter/alpaca"`, and in another it was the correct `"out/adapter_v2/alpaca"`. Fixed the "wrong" path.
> Fix adapter v2 output path

- chat/base.py
- finetune/adapter.py
- generate/adapter.py
- generate/adapter_v2.py
- generate/base.py
Strict loading is useful as it enforces that your checkpoint gets loaded as you expect.
In the case of the fine-tuned checkpoints, we can merge them to the pre-trained one before loading so that `strict=True` can be used.
Additionally, we only set `strict=False` if quantization is used. This is because of https://github.com/Lightning-AI/lit-parrot/pull/72#issuecomment-1567317405
> Stricter loading of checkpoints

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/lora.py
- lit_parrot/speed_monitor.py
- lit_parrot/utils.py
- pretrain/openwebtext.py
- pretrain/redpajama.py
- scripts/prepare_openwebtext.py
- scripts/prepare_redpajama.py
- tests/test_prepare_redpajama.py
Part of https://github.com/Lightning-AI/lit-parrot/pull/123
openwebtext with FSDP requires https://github.com/Lightning-AI/lightning/pull/17832
Follow-ups:
- Add speed monitoring to fine-tuning and the other redpajama pre-training script
- Write pretaining howto
- XLA support
> Pretrain openwebtext script with speed monitoring

- lit_parrot/speed_monitor.py
Now that we know the difference between estimated and measured, we might want to completely replace estimated.
> Add estimated FLOPs comment

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/lora.py
- generate/adapter.py
- generate/adapter_v2.py
- generate/base.py
- generate/lora.py
- lit_parrot/utils.py
- pretrain/openwebtext.py
- pretrain/redpajama.py
- quantize/gptq.py
See posted comments for in-depth explanations.
Memory usage was gathered with
```python
with torch.profiler.profile(record_shapes=True, profile_memory=True, with_stack=True) as p:
...
from torch.cuda._memory_viz import profile_plot
with open('memory.html', 'w') as f:
f.write(profile_plot(p))
```
and setting
```diff
-    max_len = max(len(s) for s in input_ids) if fabric.device.type != "xla" else max_seq_length
+    max_len = max_seq_length
```
With the changes in this PR, running `python finetune/adapter.py --checkpoint_dir checkpoints/tiiuae/falcon-7b --precision 16-true` with `max_seq_length=1079` goes from 23.10 to 22.82 GB maximum memory allocated.
Huge thanks to @robieta for helping debug the `backward` memory spike
> Memory usage improvements

- lit_gpt/lora.py
- tests/test_lora.py
Fixes
```python
File "/home/carlos/lit-parrot/finetune/lora.py", line 294, in <module>
CLI(setup)
File "/home/carlos/venv/lib/python3.10/site-packages/jsonargparse/cli.py", line 85, in CLI
return _run_component(component, cfg_init)
File "/home/carlos/venv/lib/python3.10/site-packages/jsonargparse/cli.py", line 147, in _run_component
return component(**cfg)
File "/home/carlos/lit-parrot/finetune/lora.py", line 61, in setup
measured_flops = measure_flops(meta_model, x)
File "/home/carlos/lit-parrot/lit_gpt/speed_monitor.py", line 293, in measure_flops
y.sum().backward()
File "/home/carlos/venv/lib/python3.10/site-packages/torch/_tensor.py", line 482, in backward
return handle_torch_function(
File "/home/carlos/venv/lib/python3.10/site-packages/torch/overrid …
```
> Fix FLOPs computation for LoRA

- scripts/download.py
A user got confused by a README included in one of the checkpoints. We should only download what we need.
> Filter downloaded files

- lit_gpt/utils.py
- tests/test_utils.py
- Tells you what you are missing
- Tells you if you didn't pass a directory
- Doesn't include the stacktrace anymore
- Removes the long list of available checkpoints which forced the user to scroll up to read the actual message.
> Improved check_valid_checkpoint_dir message

- README.md
- chat/base.py
- generate/adapter.py
- generate/adapter_v2.py
- generate/base.py
- generate/full.py
- generate/lora.py
- lit_gpt/config.py
- lit_gpt/utils.py
- notebooks/falcon-inference.ipynb
- quantize/bnb.py
- quantize/gptq.py
- requirements.txt
- tutorials/inference.md
- tutorials/quantize.md
Adds 4-bit quantization support for inference.
Finetuning should be addressed with #176, but this is a first step in that direction.
Updated doc can be read in https://github.com/Lightning-AI/lit-gpt/blob/carmocca/bnb-0.40/tutorials/quantize.md
> Bitsandbytes 4-bit quantization support

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- tests/test_full.py
Hi there 👋 
As discussed in another [PR](https://github.com/Lightning-AI/lit-gpt/pull/248) this PR will apply nifty formatting for large numbers, which in the case of this project - number of trainable/non-trainable parameters.
As described in Python [docs](https://docs.python.org/3/library/string.html#format-specification-mini-language):
> The ',' option signals the use of a comma for a thousands separator.
So if you provide comma as an argument for formatting it will separate thousands in the number. Comes handy when the number is pretty large: easier to spot either this is 8 or 80 million:
> Use thousands separator in number of parameters output

- finetune/lora.py
- lit_gpt/config.py
- lit_gpt/lora.py
- tests/test_lora.py
- tutorials/finetune_lora.md
This is an experiment (perhaps it needs to be a `Draft`?) to apply LoRA to not only to query and value matrices, but to:
- query
- key
- value
- projection
- MLP
- head
as described in this [issue](https://github.com/Lightning-AI/lit-llama/issues/350) (in Lit-LLaMa repo).
Changes include porting `Linear` class from Microsoft's repo in order to use it as a replacement of `nn.Linear`. MergedLinear is for attention operations, Linear - for everything else.
So now experiments could be run within CLI by providing arguments:
```bash
python finetune/lora.py --checkpoint_dir ... --query_lora True --key_lora True --value_lora True --projection_lora True --mlp_lora True --head_lora True
```
*Naming is lame, I know, so I need a help with it.*
By default (if to not provide any arguments) for …
> Support LoRA for all Linear layers

- finetune/lora.py
- lit_gpt/lora.py
- tests/test_lora.py
Hi there 👋 
That's basically a leftover from my previous PR that I totally forgot to add.
Despite support of creating `LoRAQKVLinear` without `lora_A/lora_B` at all (if `enabled_lora=(False, False, False)`) by checking 
```python
if self.r > 0 and any(self.enable_lora)
```
in `__init__` and `train` methods, that for some reason hasn't been done in `forward` method (even in the orig code), so if someone wants to apply LoRA to projection head only - it's gonna fail.
> Support lora with disabled qkv

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- pretrain/openwebtext.py
- pretrain/openwebtext_trainer.py
- pretrain/redpajama.py
This patch ensures that the model gets initialized with random weights generated from the same seed across all processes. The seed is still randomized for data-loading to ensure we have different data shards per process.
> Fix initialization of parameters in FSDP

- README.md
- lit_gpt/adapter.py
- lit_gpt/model.py
The API can be found at https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/flash_attn_interface.py
It has some special functions for MQA and GQA. See `varlen` and `kvpacked` variants. Using them would be more efficient but it would complicate the implementation considerably and PyTorch doesn't support these. For this reason, I only added support for the basic case of having separate `q`, `k`, `v` tensors of equal size
> Multi-query attention and grouped-query attention. Multi-query attention (MQA) [15] and groupedquery attention (GQA) [1] are variants of attention where multiple heads of query attend to the same head of
key and value, in order to reduce the size of KV cache during inference. Instead of having to duplicate the
key and value heads for the computation, we …
> Support Flash Attention 2

- pretrain/openwebtext.py
- pretrain/openwebtext_trainer.py
The openwebtext training scripts (fabric, trainer) have inefficient data-loading code inherited from nano-GPT. When training larger model sizes, the GPU is noticably waiting on  data from the host. This PR adds a DataLoader with num_workers>0 to prepare the batches async. 
To ensure that shuffling is randomized with a different seed in each worker, we can now conveniently set `seed_everything(..., workers=True)` too.
> Remove dataloading bottlenecks in openwebtext pretraining scripts

- tutorials/quantize.md
Hi there 👋 
Since `bitsandbytes` only supports `CUDA` device and `Linux` operating system I decided that it worth mentioning it in the quantize tutorial.
> Make a note that bitsandbytes only support Cuda and Linux.

- tutorials/download_llama_2.md
- tutorials/finetune_adapter.md
- tutorials/finetune_full.md
- tutorials/finetune_lora.md
- tutorials/inference.md
- tutorials/oom.md
- tutorials/quantize.md
- tutorials/tpus.md
Pretty small fixes for markdown files:
1. [MD009](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md009.md) - Trailing spaces.
Rationale: Except when being used to create a line break, trailing whitespace has no purpose and does not affect the rendering of content.
2. [MD031](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md031.md) - Fenced code blocks should be surrounded by blank lines.
Rationale: Aside from aesthetic reasons, some parsers, including kramdown, will not parse fenced code blocks that don't have blank lines before and after them.
3. [MD034](https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md034.md) - Bare URL used. 
Rationale: Without angle brackets, a bare URL or email isn't converted into a link by some Markdown parsers.
4. …
> Tutorial markdowns small fixes

- finetune/lora.py
- generate/lora.py
- lit_gpt/lora.py
- tests/test_lora.py
Fixes #161
Refactors the merging of LoRA weights.
**Before:**
Merging was implemented in `model.eval()`, and "unmerging" was implemented in `model.train()`. This was done to speed up the forward pass for inference where LoRA matrices aren't needed. Unmerging was needed to bring the weights back for optimization (assuming validation is interleaved at periodic intervals with training). However, due to the fact that the `eval()/train()` methods access the weights, they are sharded and so computations on them can't be performed directly. In FSDP, the full weights are only available during the forward. 
**Now:**
We don't need merging and unmerging implemented in `eval()/train()`. Our validation loop will be slightly slower but we can afford that cost since we're not validating extensively. The …
> Refactor LoRA weights merging + support FSDP

- README.md
- quantize/gptq.py
- tutorials/download_freewilly_2.md
- tutorials/download_llama_2.md
Being a hairsplitter, this PR addresses the LLaMA vs Llama 2 capitalization. Like others pointed out to me, for Llama 2 the official spelling does not use capitalization. (Others like the NeurIPS challenge organizers also distinguish between LLaMA and Llama 2 :))
> Use modernized llama spelling

- scripts/convert_lit_checkpoint.py
- tests/test_convert_lit_checkpoint.py
This PR resolves #293 by adding support for converting Lit-GPT NeoX models back to their original format.
> Convert Lit-GPT GPT-NeoX Model Format to Original GPT-NeoX Format

- tutorials/quantize.md
I added a 32-bit baseline and extended the explanations a bit.
> Extend explanations in quantize doc and add 32-bit baseline

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- pretrain/openwebtext.py
- pretrain/redpajama.py
There was a `fabric.print()` statement before `fabric.launch()`, which cannot happen on TPUs. The solution was to move `fabric.print()` into the launched function
> [TPU] fixed bug for finetuning and pretraining

- tests/test_lora.py
Tests now check that LoRA is applied to only the target layers (and for both MLP classes).
> A more robust LoRA utilization test

- lit_gpt/lora.py
Hi there 👋 
This PR contains simplification of the logic in `forward` methods.
Now there is no need for so many if statements.
Essentially we need to do the forward pass with the pretrained weights *anyway* and add to the result output from LoRA weights if the conditions are met. Thus only one if statement is needed.
In addition in this PR I also removed transposing function from each merge/forward method and created a class method instead.
> Simplify forward pass in LoRALinear layers

- README.md
Given that Lit-GPT was elected as the official starter kit for the NeurIPS 2023 challenge, I thought it may be worthwhile mentioning it in the Readme. 
It's really nice that the challenge has the 1 day 1 GPU restriction, and I bet a lot of researchers might be interested in participating but haven't heard of the challenge yet.
> Add note about neurips challenge

- lit_gpt/lora.py
- tests/test_lora.py
Hi there 👋 
The rationale for this PR is that anyone who uses modules from lora file (maybe for neurips challenge) should know if `merge` method in fact cannot merge the weights either because `rank` is set to zero or to a negative value (which disables LoRA and leaves only pretrained weights) or through setting all `enable_lora` booleans as False.
`Verbose` argument was added to control it.
For example we can intentionally disable LoRA weights for let's say `projection` layer but still want to use `LoRALinear` class. It's possible to do by setting rank to be zero. In such case we don't need to pollute logs with information that merging is not possible as it's an expected behavior.
For instance in `merge_lora_weights`.
In contrary anyone who explicitly calls `merge` method by default …
> Mark LoRA and pretrained weights as merged only when it's possible

- generate/lora.py
- tests/test_generate_lora.py
Essentially a copycat of tests for base generation and generation with an adapter, but for LoRA.
Includes two specific to LoRA tests:
1. checks that LoRA's global variables are specified.
2. checks that LoRA is applied to at least one layer (otherwise what's the point of running generation with LoRA).
Ideally to check that the instance of Config class inside `generate/lora.py:main` contains lora-specific arguments, but couldn't find how to mock init method of Config class, similar to:
https://github.com/Lightning-AI/lit-gpt/blob/21a6d9ee1884998ef4ed500b89d5bd3a5445983d/tests/test_generate.py#L30-L36
(if it's even possible).
> Tests for generation with LoRA

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
This is an edge case for FSDP. 
`model.device` is normally equal to `fabric.device`, except in the case of FSDP for which the device attribute is not updated. In the scripts below, we are interested in moving an input tensor to the right device, so we use `fabric.device`. 
In prepareation of #351 for these scripts.
> Use `fabric.device` instead of `model.device`

- tests/test_utils.py
Extends the existing test for the `utils.chunked_cross_entropy`, with parity assertions against the raw `torch.nn.functional.cross_entropy` output.
Concerns were raised in https://github.com/Lightning-AI/lit-gpt/issues/328#issuecomment-1656871814 that they are not equivalent.
> Extend the unit test for chunked cross entropy

- lit_gpt/lora.py
- tests/test_lora.py
Replaces inheritance with composition for the LoRA Linear layers.
This should workaround the issue described in https://github.com/pytorch/xla/pull/5437 and https://github.com/Lightning-AI/lit-gpt/issues/352
Fixes https://github.com/Lightning-AI/lit-gpt/issues/352
> Use composition with LoRA

- tutorials/evaluation.md
I think we should lead with the default setting most people will be interested in. That is evaluating on all tasks. I also added a link to the task table, which is super useful (otherwise, it may look like we only support 2 tasks).
> Add more explanation to evaluation tutorial

- scripts/convert_lit_checkpoint.py
- tests/test_convert_lit_checkpoint.py
This PR makes all arguments of `convert_lit_checkpoint` required. More context as to why is provided below.
The default output during finetuning saves checkpoints in the shown manner.
This structure does not set the model name correctly when using the current method shown below.
```python
def convert_lit_checkpoint(
*,
checkpoint_name: str,
checkpoint_dir: Path = Path("checkpoints/tiiuae/falcon-7b"),
model_name: Optional[str] = None,
) -> None:
if model_name is None:
model_name = checkpoint_dir.name
config = Config.from_name(model_name)
```
Making all args required allows users to convert exactly the finetuned model they intend to convert with something similar to:
```sh
python scripts/convert_lit_checkpoint.py \
--checkpoint_name lit_model_adapter_finetuned.pth  \
--checkpoint_dir …
```
> Make all args required in `convert_lit_checkpoint`

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
Whilst getting XLA FLOP numbers, the MFU was >1. Give it's meant to be a percentage, it couldn't be correct.
Noticed 2 issues:
- We were computing the estimated FLOPs for a batch of the model's context length, even though the samples are often smaller
- We were computing estimated FLOPs for the full model without the frozen weights
Note that XLA will use padding to the longest sample in the dataset, so the FLOP numbers will be inflated as they don't take padding into account. In this case, samples/sec would be a more realistic metric.
> Improve FLOPs calculation for finetuning scripts

- lit_gpt/lora.py
- tests/test_lora.py
Unblocks https://github.com/Lightning-AI/lit-gpt/pull/275 by avoiding https://github.com/Lightning-AI/lit-gpt/pull/275#issuecomment-1677703307
I haven't noticed an increase in peak memory usage
> Avoid in-place operations in LoRA forward

- lit_gpt/speed_monitor.py
The calculations for `tokens_per_sec` (and `device/tokens_per_sec`) in `SpeedMonitor` are wrong, specifically an overestimation by a factor of `window_size` (default to 100). To fix, we need multiply `samples_per_second` by the mean number of tokens per sample (instead of multiplying by the **sum** of of number of tokens per sample over the last `window_size` batches, which is done currently).
For comparison, see the reference implementation:
```python
try:
max_seq_len = state.dataloader.dataset.max_seq_len  # type: ignore
logger.log_metrics({'throughput/tokens_per_sec': samples_per_sec * max_seq_len})
logger.log_metrics({'throughput/device/tokens_per_sec': dev_samples_per_sec * max_seq_len})
```
https://github.com/mosaicml/composer/blob/f2a2dc820cb75023b9eb7c46fdfd25273712abd0/composer/ca …
> Fix `tokens_per_sec`  calculation in `SpeedMonitor`

- .github/azure-gpu-tests.yml
- .github/workflows/cpu-tests.yml
- README.md
- quantize/gptq.py
- requirements.txt
- scripts/prepare_openwebtext.py
- setup.py
- tutorials/download_falcon.md
- tutorials/download_pythia.md
- tutorials/download_redpajama_incite.md
- tutorials/download_stablelm.md
- tutorials/evaluation.md
- tutorials/quantize.md
Fixes https://github.com/Lightning-AI/lit-gpt/issues/323
Fixes https://github.com/Lightning-AI/lit-gpt/issues/278
Most of our dependencies are optional. Do not include them in our `requirements.txt`
> Do not install unnecessary dependencies

- chat/base.py
- eval/lm_eval_harness.py
- eval/lm_eval_harness_lora.py
- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- generate/adapter.py
- generate/adapter_v2.py
- generate/base.py
- generate/full.py
- generate/lora.py
- lit_gpt/utils.py
- pretrain/openwebtext.py
- pretrain/openwebtext_trainer.py
- pretrain/redpajama.py
- quantize/gptq.py
Hi there 👋 
This PR addresses the issue when `bf16-true` is used by default even for cards that don't support it: Nvidia T4 and V100 for example (which are quite popular).
Why for the training `bf16-mixed` is used and not `bf16-true` you may ask?
As @carmocca stated:
> there's many results across tutorials and blogposts that use the current default, so changing this will invalidate them if they weren't explicitly specifying the precision
---
Tested on T4 and A10G: `16-true/mixed` and `bf16-true/mixed` respectively are applied by default.
CPU also by default uses `bf16` precision.
Fixes #327
> Use bf16 as default only if supported

- lit_gpt/adapter_v2.py
- lit_gpt/utils.py
- tests/test_adapter_v2.py
Follow-up to https://github.com/Lightning-AI/lit-gpt/pull/414
Tested with
generate_old.py
```python
import rich
import torch
from lit_gpt.adapter import GPT
from lit_gpt.adapter_v2 import add_adapter_v2_parameters_to_linear_layers
m = GPT.from_name("pythia-70m")
add_adapter_v2_parameters_to_linear_layers(m)
print(m)
sd = m.state_dict()
rich.print(sorted(sd))
torch.save(sd, "old_adapter_v2_ckpt")
```
load_old.py
```python
import rich
import torch
from lit_gpt.adapter_v2 import GPT
sd = torch.load("old_adapter_v2_ckpt")
rich.print(sorted(sd))
m = GPT.from_name("pythia-70m")
print(m)
m.load_state_dict(sd)
```
```shell
git checkout fdc142b0a9940aa1741bbaaca9883eddf09a2c94
python generate_old.py
git checkout carmocca/add-compatibility-for-older-adapter-v2-checkpoints
python load_old.py
```
> Add compatibility for previous adapter v2 checkpoints

- README.md
- scripts/convert_lit_checkpoint.py
- tests/test_convert_lit_checkpoint.py
Raises `Exception` to inform users that converting models finetuned with `lora`, `adapter`, and `adapter_v2` is not yet supported.
See #374 and #355.
> Add `convert_lit_checkpoint::check_conversion_supported`

- scripts/convert_hf_checkpoint.py
- scripts/convert_lit_checkpoint.py
- tutorials/download_falcon.md
- tutorials/download_freewilly_2.md
- tutorials/download_llama_2.md
- tutorials/download_longchat.md
- tutorials/download_openllama.md
- tutorials/download_pythia.md
- tutorials/download_redpajama_incite.md
- tutorials/download_stablelm.md
- tutorials/download_vicuna.md
This is useful for cloud machines with limited system memory (RAM) where you know you'll be loading into a specific dtype before conversion.
Also to avoid this FSDP error:
```python
File "/home/carlos/lit-parrot/finetune/lora.py", line 126, in main
model = fabric.setup_module(model)
File "/home/carlos/venv/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 282, in setup_module
module = self._strategy.setup_module(module)
File "/home/carlos/venv/lib/python3.10/site-packages/lightning/fabric/strategies/fsdp.py", line 279, in setup_module
module = FullyShardedDataParallel(
File "/home/carlos/venv/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 456, in __init__
_auto_wrap(
File "/home/carlos/venv/lib/python3.10/site-packages/torch/distribut …
```
> Support converting the checkpoint dtype

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- lit_gpt/speed_monitor.py
- pretrain/openwebtext.py
- pretrain/openwebtext_trainer.py
- pretrain/redpajama.py
Can be tested with
```python
from lit_gpt.adapter import GPT, mark_only_adapter_as_trainable
from lit_gpt.speed_monitor import measure_flops, estimate_flops
import torch
micro_batch_size = 2
with torch.device("meta"):
model = GPT.from_name("falcon-40b")
mark_only_adapter_as_trainable(model)
estimated_flops = estimate_flops(model) * micro_batch_size
print(f"Estimated TFLOPs: {estimated_flops * 1 / 1e12:.2f}")
x = torch.randint(0, 1, (micro_batch_size, model.config.block_size))
measured_flops = measure_flops(model, x)
print(f"Measured TFLOPs: {measured_flops * 1 / 1e12:.2f}")
```
Before:
```text
Estimated TFLOPs: 1077.76
Measured TFLOPs: 708.77
```
After:
```text
Estimated TFLOPs: 768.02
Measured TFLOPs: 708.77
```
The discrepancy after is within the 10% as described in …
> Add support for estimated flops with frozen parameters

- lit_gpt/adapter.py
- lit_gpt/adapter_v2.py
- lit_gpt/model.py
The only performance difference would be in the flash-attn case, which removed one redundant transpose.
Replacing `repeat_interleave` is just for the simpler operator.
> Minor model operator simplifications

- eval/lm_eval_harness_lora.py
The LoRA version tried to import 
```bash
from lm_eval_harness import EvalHarnessAdapter
```
which does not exist. 
I believe this should have been 
```bash
from lm_eval_harness import EvalHarnessBase
```
> Fix class import in LoRA Eval Harness

- lit_gpt/utils.py
- tests/test_utils.py
PyTorch 2.0+ allows storing attributes to tensors, but then the return of `__reduce_ex__` changes.
Fixes: #371 
Thank you @MrJungle1 for reporting and @carmocca for flagging this to me with a repro.
> Fix incremental_save when using Python attributes to tensors

- lit_gpt/config.py
Hi there 👋 
I noticed a small inconsistency when `padded_vocab_size` is provided and it's smaller than the value by default for `vocab_size`:
```bash
main ~/repos/lit-gpt python generate/base.py --prompt "Hello, my name is" --checkpoint_dir checkpoints/NousResearch/Nous-Hermes-13b --precision bf16-true --quantize bnb.nf4
Loading model 'checkpoints/NousResearch/Nous-Hermes-13b/lit_model.pth' with 
{
'org': 'NousResearch', 'name': 'Nous-Hermes-13b', 'block_size': 2048, 
---> 'vocab_size': 50254, <---
'padding_multiple': 512,
---> 'padded_vocab_size': 32001, <---
'n_layer': 40, 'n_head': 40, 'n_embd': 5120, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'n_query_groups': 40, 'shared_attention_norm': False, '_norm_class': 'RMSNorm', 'norm_eps': 1e-06, '_mlp_class': …
```
> Vocab size shouldn't be larger than padded vocab size

- lit_gpt/speed_monitor.py
Support FP8/transformer-engine precision as added to lightning in https://github.com/Lightning-AI/lightning/pull/17597
> fix: support transformer-engine (h100 fp8) in speed_monitor

- scripts/prepare_alpaca.py
- scripts/prepare_dolly.py
- scripts/prepare_lima.py
cc @rasbt 
Variables that are exposed in the CLI don't need to be also defined as globals. Users could change the signature default already
> Remove globals that are already exposed in the CLI

- scripts/download.py
Previously produced `NameError: name 'token' is not defined`. Now, fixed `token=token` to `token=access_token`.
> Fix use of "access_token"

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- pretrain/openwebtext.py
- pretrain/redpajama.py
Performance improvement that avoids moving the val losses to the host before stacking them. I had to make this change to the xla finetuning scripts
> Reduce `.item()` calls during validation

- tests/test_lora.py
The `@pytest.mark.xfail(raises=AttributeError, strict=False)` decorator was hiding a real AttributeError after #388
> Fix broken LoRA test

- lit_gpt/utils.py
Hi there 👋 
Didn't know that in Fabric `mps` is not supported with Radeon GPUs, so when I ran the script, and it worked fine, I thought that's all is good. Maybe it is worth to display what precision and device is used in the training/generation log?
Anyway, apparently `mps` doesn't support `bf16` precision and by default exactly this precision was used with this device type.
> MPS device doesn't support `bf16` precision.

- tutorials/convert_lit_models.md
- tutorials/download_code_llama.md
- tutorials/download_freewilly_2.md
- tutorials/evaluation.md
- tutorials/finetune_full.md
- tutorials/finetune_lora.md
- tutorials/neurips_challenge_quickstart.md
- tutorials/oom.md
- tutorials/prepare_dataset.md
- tutorials/pretrain_redpajama.md
- tutorials/quantize.md
- xla/README.md
Hi there 👋 
I've noticed that in some markdown files [!NOTE] label is not rendered correctly because of the appended characters.
Also, I standardized all "note" labels to be only [!NOTE] and not [!NOTE]\\.
Fixed trailing white spaces and removed unnecessary empty lines except those that Sebastian added lately: don't understand why he likes so much that many empty spaces but feel like if I delete them - something is gonna happen to me 😆 🙀.
---- 
@rasbt if you're reading this, in VSCode: 	
```text
"files.trimTrailingWhitespace": true,
```
😉😉
> Markdown chores: NOTE rendering, trailing spaces and multiple empty lines fix

- chat/base.py
- eval/lm_eval_harness.py
- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- generate/adapter.py
- generate/adapter_v2.py
- generate/base.py
- generate/full.py
- generate/lora.py
- lit_gpt/adapter.py
- lit_gpt/adapter_v2.py
- lit_gpt/lora.py
- lit_gpt/model.py
- tests/test_adapter.py
- tests/test_adapter_v2.py
- tests/test_chat.py
- tests/test_full.py
- tests/test_generate.py
- tests/test_generate_adapter.py
- tests/test_generate_lora.py
- tests/test_lora.py
- tests/test_model.py
- xla/finetune/adapter.py
- xla/generate/adapter.py
- xla/generate/base.py
Advantages:
- removes the `rope_cache` instantiation from `forward`
- One less argument that is passed through the models
- The rope cache now uses the `max_seq_length` for the length, instead of `block_size`. Saving memory if the former is smaller
> Manage the `max_seq_length` through a property

- scripts/merge_lora.py
- tests/test_merge_lora.py
- tutorials/finetune_lora.md
Provide a script for merging LoRA weights as described in #494. 
Fixes #517
If you think this is a good idea, this PR provides an example of how to implement such a script.
**Finetune on a dataset as usual:**
```bash
python scripts/download.py --repo_id tiiuae/stablelm-base-alpha-3b
```
```bash
python scripts/prepare_alpaca.py
```
```bash
python finetune/lora.py \
--checkpoint_dir "checkpoints/stabilityai/stablelm-base-alpha-3b/" \
--data_dir "data/alpaca" \
--out_dir "out/lora_stage_1/stablelm-base-alpha-3b/"
```
**Merge lora weights with model:**
```bash
python scripts/merge_lora.py \
--checkpoint_dir "checkpoints/stabilityai/stablelm-base-alpha-3b/" \
--lora_path "out/lora_stage_1/stablelm-base-alpha-3b/lit_model_lora_finetuned.pth" \
--out_dir …
```
> Merge lora script

- chat/base.py
- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- generate/adapter.py
- generate/adapter_v2.py
- generate/base.py
- generate/full.py
- generate/lora.py
- lit_gpt/adapter.py
- lit_gpt/adapter_v2.py
- lit_gpt/lora.py
- lit_gpt/model.py
- tests/test_generate.py
- tests/test_model.py
- xla/finetune/adapter.py
- xla/generate/adapter.py
- xla/generate/base.py
Refactors the model definition to move the KV cache and mask creation and management out of `forward`.
This should reduce the risk of recompilation with compilers such as xla or torchdynamo.
The KV cache is now managed with a `nn.Module` to have it registered automatically. This module has no parameters so there shouldn't be any checkpointing issues
credit to @Chillee for the idea
> Move KV cache management out of forward

- tests/test_lora.py
Hi there 👋 
If to run test `test_lora_qkv_linear_weights_merged_status` on Nvidia T4 - it will fail as this graphics card doesn't support `bf16` precision.
The problem is that this precision is hard-coded, but this PR fixes it.
> test_lora: `bf16` precision shouldn't be hard-coded as it might not be supported.

- finetune/full.py
- finetune/lora.py
- generate/adapter.py
- generate/adapter_v2.py
- generate/full.py
- generate/lora.py
- lit_gpt/model.py
- lit_gpt/utils.py
- tests/test_full.py
- tests/test_lora.py
I'm resubmitting the previously rejected changes in #351. 
Makes the scripts compatible to run with meta-device init in FSDP via `fabric.init_module(empty_init=True)`. Also enables `fabric.load_raw()` which uses lazy-loading internally. The combined changes make it possible to initialize very large models and load the checkpoint in an efficient way without using up all available CPU RAM.
I tested convergence on both scripts.
> FSDP meta-init for full and LoRA finetuning 

- lit_gpt/utils.py
- tests/test_utils.py
When using `--lora_path` or `--adapter_path` in the `generate/` scripts & someone accidentally specifies a non-existing path or a folder instead of a checkpoint file there was a `PytorchStreamReader failed` error. I added more specific error messages to help users debug input path issues.
> Check if the checkpoint path exists before lazy loading it

- scripts/prepare_longform.py
- tutorials/prepare_dataset.md
Adds the LongForm dataset.
LongForm is a semi-synthetic dataset based on raw text corpora for which the instructions were generated via an LLM. For more details about the instruction-generation process, please refer to the [LongForm research paper](https://arxiv.org/abs/2304.08460) by Köksal et al. According to the research paper, a Llama 7B model trained on LongForm achieves substantially better performance than the same Llama model trained on the 2x larger Alpaca dataset.
LongForm consists of 23,652 training samples, 2,042 validation samples, and 2,045 test samples. (In Lit-GPT, the validation samples are currently not used.)
The more detailed dataset composition is as follows based on a table taken from the [dataset repository](https://github.com/akoksal/LongForm):
| **Type** …
> Add LongForm dataset (better than Alpaca)

- .github/workflows/cpu-tests.yml
- README.md
- lit_gpt/__init__.py
- notebooks/falcon-inference.ipynb
- tutorials/neurips_challenge_quickstart.md
Avoids issues like https://github.com/Lightning-AI/lit-gpt/issues/582
The previous instructions will now try to install PyTorch 2.2 nightly
> Recommend release candidate

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- lit_gpt/utils.py
- pretrain/openwebtext.py
- pretrain/openwebtext_trainer.py
- pretrain/redpajama.py
- xla/finetune/adapter.py
The custom implementation in this repo has the issue fixed in https://github.com/Lightning-AI/lightning/pull/18567
Since we no longer keep the full metrics history in memory and write it every time, it's not straightforward to do the aggregation by `step` on the go.
This PR removes it, the csv file can be post-processed after training with something like:
```py
import pandas as pd
df = pd.read_csv('metrics.csv')
combined_df = df.groupby('step').sum()
print(combined_df)
```
> Drop custom CSV logger implementation

- tutorials/finetune_lora.md
For Llama 2 7B I also needed to copy the `tokenizer.model` file. (I am not sure if all models now need it).
> Update finetune_lora.md docs

- tutorials/finetune_lora.md
- tutorials/quantize.md
Hi there 👋 
Part of #622 
Essentially `tutorials/finetune_lora.md` and `tutorials/quantize.md` contain times required to train and generate respectively, but they were obtained with CUDA v11.8, and the current main installs CUDA v12.1. On the latest version a hardware utilization is better and thus the time to train/generate should be smaller. 
Before the numbers are updated with the latest version of CUDA I think it's important to mention the version on which they were obtained.
> Mention that the numbers in markdowns were obtained with CUDA 11.8

- README.md
Hello there 👋 
Part of #511.
Someone might want to use `Lit-GPT` as a part of an existing project. If it's a mature commercial project, then most likely it's using a specific version of Python, which will not be updated any time soon. As a result, it might be helpful for such a person to know what Python versions are supported.
For the core functionality, the main restrictor is `Lightning`, so I decided for simplicity to reuse the badge from PyTorch-Lightning repo. 
As seen in [these](https://github.com/Andrei-Aksionov/lit-gpt/actions/runs/6468597163/job/17560942575) GitHub Actions, only 3.9-3.11 are supported.
3.12 is not supported as, for now, it's not possible to install PyTorch with this version of Python. Soon-to-release version of Lightning will support only up to 3.11, so the badge …
> A badge with supported Python versions

- tutorials/pretrain_redpajama.md
We had super long commands in the redpajama docs which made them really heard to read (impossible without scrolling)
> Wrap long command line arguments in redpajama docs

- README.md
- lit_gpt/model.py
Closes #395
Closes #637
For now, the inconvenience of compiling `flash-attn` is not worth it, and there are other speed benefits in using torch 2.2 anyway. This can be re-evaluated in the future if `flash-attn` becomes faster again, or we decide to use a more custom kernel from theirs.
> Drop flash-attn 2 in favor of PyTorch's version

- pretrain/openwebtext.py
- pretrain/redpajama.py
Minor fix to resuming checkpoint path . Currently, resuming takes the last path of the sorted list. However, the sorted list may not return a list sorted in ascending `iter_num`. For example,
```
from pathlib import Path
out_dir = Path("out") / "openwebtext"
paths = [out_dir / f"iter-{iter_num}-ckpt.pth" for iter_num in range(0, 1100000, 40000)]
print(sorted(paths))
```
returns the following. Note that the list isn't sorted (i.e. `iter-1080000` should be the last, but it isn't). Thus resuming will not take the latest checkpoint in this case.
```
[PosixPath('out/openwebtext/iter-0-ckpt.pth'), PosixPath('out/openwebtext/iter-1000000-ckpt.pth'), PosixPath('out/openwebtext/iter-1040000-ckpt.pth'), PosixPath('out/openwebtext/iter-1080000-ckpt.pth'), …
```
> Fix resuming checkpoint path bug

- tutorials/finetune_lora.md
- tutorials/resource-tables.md
I made a resource table that I think will be helpful for people who have questions about the resource requirements. Also, it could be a useful reference for spot checking new select PRs to see whether they improve/decrease performance and memory requirements.
One question though is regarding the runtime of the multi-GPU cases. If I run `max_iters = 1000` on 1 GPU, it will do 1000 iterations. If I run the same code on 2 GPUs, is it actually iterating through 2000 examples (even though it prints 1000 iterations)? 
EDIT: I want to add 8-GPU tests some time too but that's currently not possible due to the 4 GPUs currently being occupied for other things)
> Resource table

- tutorials/resource-tables.md
Sorry, I am not sure how that happened, but I just saw that the headers spelled it "Finetinung" instead of "Finetuning" 🤦‍♂️
> Fix typo in the resource-tables.md

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
The current FLOPs per batch computation assumes that all batches have a sequence length (`T`) equal to the longest in the dataset.
This is very far from true when using our finetuning datasets and scripts (see the histograms at https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/prepare_dataset.md). The magnitude of this depends on the `max_seq_length` value used when preparing the dataset.
This default behavior of the dataset preparation scripts results in extremely unrealistic (optimistic) FLOPs and MFU values. This PR removes them to avoid confusion.
An alternative to this solution would be to get the estimated/measured flops per batch, but this would have an overhead per iteration (https://github.com/Lightning-AI/lit-gpt/pull/409 tried this)
The XLA finetuning script is …
> Remove FLOPs calculation from finetuning scripts

- lit_gpt/tokenizer.py
- tests/test_tokenizer.py
Two small improvements:
- If the checkpoint directory does not exist, show a meaningful error (instead of the NotImplementedError)
- Allow passing in a string for a path, rather than just pathlib Path
cc @carmocca
> Tokenizer usability improvements

- scripts/download.py
- tutorials/pretrain_redpajama.md
During pre-training, downloading the full model weights of an existing checkpoint is unnecessary when one only wants the tokenizer to preprocess the dataset.
> Add flag to download the tokenizer only

- lit_gpt/utils.py
- requirements-all.txt
Hi there 👋 
Fixes #707 
Bitsandbytes starting from version `0.41.2` uses `quant_state` as a class, not as a list: https://github.com/TimDettmers/bitsandbytes/commit/61a4a20da91b7f780a98d3ff8235f1455835ecf2.
As a result, when trying to access the shape by the index
https://github.com/Lightning-AI/lit-gpt/blob/d9283f420be2ee3b9af77b2e12edf92aa200379e/lit_gpt/utils.py#L35
... we get:
> TypeError: 'QuantState' object is not subscriptable
------
As proposed in #710 maybe we indeed need to pin version of BNB since such breaking changes might appear again?
> BNB>=0.41.2 uses quant_state as a class, not as a list

- chat/base.py
- generate/base.py
This script shows the issue:
```python
import torch
top_k = 2
for _ in range(10):
logits = torch.randint(0, 50, (1, 5, 6))
logits = logits[:, -1]
top_k = min(top_k, logits.size(-1))
print(f"{top_k=}")
print(f"{logits=}")
v, _ = torch.topk(logits, top_k)
original = torch.where(logits < v[:, -1:], -999, logits)
print(f"{original=}")
v, i = torch.topk(logits, top_k)
new = torch.full_like(logits, -999).scatter_(-1, i, v)
print(f"{new}")
torch.testing.assert_close(original, new)
```
If two or more of the highest k logits have the same value, `torch.where` will return all meaning that sampling is done for more than k elements.
The code should also be faster since we're reusing the top-k indices to scatter the logits
```python
import time
import torch
torch.set_float32_matmul_precision('high') …
```
> Fix top_k bug with collisions

- .github/azure-gpu-test.yml
- tests/test_lora.py
For now, it runs all tests. We might filter out CPU tests in the future
> Enable CUDA testing

- chat/base.py
- generate/adapter.py
- generate/adapter_v2.py
- generate/base.py
- generate/full.py
- generate/lora.py
Hi there 👋 
As was asked in #690, a user might expect that the generated text will be consistent from run to tun.
Since the seed was already fixed in `generate/base.py`, this PR extends it to all other generation scripts.
> Fix seed in all generation scripts.

- requirements-all.txt
- tests/test_lm_eval_harness.py
Hi there 👋 
Life is interesting.
A couple of days after @carmocca finished [fighting](https://github.com/Lightning-AI/lit-gpt/pull/747) with forcing `lm_eval` to work under Python3.8, the changes [were made](https://github.com/EleutherAI/lm-evaluation-harness/pull/1004) to the 3rd party repo, so now `lm_eval` supports Python3.8 out of-the-box 🎉.
This PR removes specific to that fight changes, as they are no longer needed.
> Remove code to force `lm_eval` to work under Python 3.8

- lit_gpt/utils.py
- tests/test_utils.py
This PR resolves an issue in loss computation when chunksize is greater than zero. The correction ensures that only prompts generated by the model contribute to the mean loss computation.
Previously, the mean was calculated across all positions of the sequence, including those within the prompt. In such cases, the loss was automatically set to 0 due to the **correct** use of `torch.nn.functional.cross_entropy` with `ignore_index=-1.` 
However, the subsequent `torch.cat(loss_chunks).mean()` considered all elements of the sequence to compute the mean, leading to an artificial reduction in the loss. This effect becomes more pronounced with longer prompts, as the denominator of the mean increases.
> Bugfix: Corrected loss computation with chunksize > 0

- scripts/download.py
Hi there 👋 
Fixes #760 
For downloading weights from HF we use `snapshot_download` function. 
One of the arguments it has is `revision` where we can provide the commit that works without issues.
That's exactly what needs to be done in case of `microsoft/phi-1_5` as breaking changes were introduced in one of the latest commits.
> Pin revision of Phi-1.5

- lit_gpt/__init__.py
- pretrain/tinyllama.py
Suppresses an excessive warning triggered in our pretraining script where `torch.compile` and FSDP are used together. See also: https://github.com/pytorch/pytorch/issues/111632
> Suppress FSDP+dynamo warning

- lit_gpt/config.py
- tests/test_config.py
- tutorials/download_tinyllama.md
Hi there 👋 
Accidentally noticed that TinyLlama project has a [more recent]() checkpoint available.
In addition, they changed `org name` to a more suitable one.
Though I kinda liked James Bond reference …
Additional question: should we also include `-Chat-v0.x` version? Just don't know why it wasn't added before.
> TinLlama: Update intermediate checkpoint

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
Right now we don't allow truncating inputs while fine tuning, the max sequence length is computed from the dataset.
This PR introduces a `max_seq_length` variable that can be used to truncate sequences and avoid OOMs on smaller devices. It is set to a very high number by default.
> Add max_seq_length to optionally allow truncating inputs

- tutorials/pretrain_redpajama.md
- tutorials/pretrain_tinyllama.md
Provides the simple git-lfs installation command that works on Ubuntu.
> Update git lfs installation instructions

- pretrain/tinyllama.py
A small refactor to the resume logic, pulling it out of the  main loop. This way, we can compute `total_t0` after the the resuming has finished, and avoiding it to be skewed.
> Refactor resume logic in tinyllama.py

- pretrain/tinyllama.py
Setting `drop_last=True` here ensures we get a constant batch size in every iteration. Not doing so could cause the shape to change and triggering torch to recompile the model's forward pass. When recompiling due to changing shapes, the generated kernels will be less specialized, leading to a performance loss in subsequent iterations.
> Set `drop_last=True` in tinyllama.py

- lit_gpt/__init__.py
Disables a wall of warning text that gets emitted during checkpointing. I propose to remove this because it is kind of annoying. I believe PyTorch should log them at debug-level, not warning level because they are not legit warnings. 
```
Validating ...
iter 848000: val loss 2.2185, val time: 12765.29 ms
Saving checkpoint to '/share/lit-tiny-llama-1.1b/step-00053000.pth'
[rank0]:[2023-12-08 02:41:10,117] torch.distributed.fsdp._optim_utils: [WARNING] CUDA Memory Summary before calling to _allgather_orig_param_states |===========================================================================|
[rank0]:[2023-12-08 02:41:10,117] torch.distributed.fsdp._optim_utils: [WARNING] |                  PyTorch CUDA memory summary, device ID 0                 |
[rank0]:[2023-12-08 02:41:10,117] …
```
> Disable FSDP state-dict profiling warnings

- pretrain/tinyllama.py
- requirements-all.txt
- tutorials/pretrain_tinyllama.md
The current script logs the instantaneous loss of the last iteration in the accumulation window, it makes the loss curve a bit noisy. This PR adds a running loss over a window the size of the gradient accumulation and logs that.
Note: Instead of using torchmetrics as a dependency, we could also implement a simple RunningMean class here in lit-gpt. Let me know what you prefer.
> Compute running loss in tinyllama.py

- generate/adapter.py
- generate/adapter_v2.py
- generate/base.py
- generate/full.py
- generate/lora.py
- tutorials/inference.md
Batch size 1 inference with FSDP is highly inefficient because there's a lot of unnecessary communication going on.
Since I'll be adding sequential inference, this fsdp is irrelevant.
Might be added back to a batched generation script, where data parallelism can be beneficial.
> Drop inference with FSDP

- README.md
Thanks for this project!
I had to search through the issues to understand how to use FA 2.
Once I realized it was automatic, I thought I'd add a clarifying bit to the readme. 
Explain that Flash Attention 2 is used automatically if Pytorch 2.2 is installed.
> Clarify how to use Flash Attention 2 (with Pytorch Nightly installed)

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- generate/base.py
- tests/test_generate.py
Seems like we missed passing the EOS token id to the generate function for the fine-tuning scripts and generate/base.py
> Always stop generation on EOS

- README.md
If the environment already had these, uninstalling torch is not enough because when a dependency imports them, it will likely fail. Example:
```python
File "/teamspace/studios/this_studio/lit-gpt/scripts/convert_hf_checkpoint.py", line 10, in <module>
from lightning.fabric.utilities.load import _NotYetLoadedTensor as NotYetLoadedTensor
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/__init__.py", line 20, in <module>
from lightning.pytorch.callbacks import Callback  # noqa: E402
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/__init__.py", line 27, in <module>
from lightning.pytorch.callbacks import Callback  # noqa: E402
File …
```
> Suggest uninstalling other torch* projects before nightly

- lit_gpt/model.py
A tiny tiny :pinching_hand: perf improvement on eager.
```markdown
eager: 15553.886890411377us
0.89549568 GB
eager: 15398.350954055786us
0.895553024 GB
```
Also resolves https://github.com/Lightning-AI/lit-gpt/pull/823#discussion_r1427943757
> Precompute the expert mask

- scripts/prepare_alpaca.py
- scripts/prepare_csv.py
- scripts/prepare_dolly.py
- scripts/prepare_lima.py
- scripts/prepare_longform.py
- tests/test_prepare_csv.py
Addresses complaints that the unused "input_ids_no_response" in the output causes confusion among users who adopt these scripts (https://github.com/Lightning-AI/lit-gpt/issues/796#issuecomment-1854667341).
> Remove `input_ids_no_response` from instruction finetuning scripts

- chat/base.py
- eval/lm_eval_harness.py
- generate/base.py
The lines
```python
for block in model.transformer.h:
block.attn.kv_cache.reset_parameters()
```
can cause issues if not run under `inference_mode`:
```python
block.attn.kv_cache.reset_parameters()
File "/home/carlos/lit-parrot/lit_gpt/model.py", line 371, in reset_parameters
torch.nn.init.zeros_(self.k)
File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/init.py", line 247, in zeros_
return _no_grad_zero_(tensor)
File "/home/carlos/nightly-env/lib/python3.10/site-packages/torch/nn/init.py", line 65, in _no_grad_zero_
return tensor.zero_()
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.
```
> Apply `inference_mode` where we `kv_cache.reset_parameters`

- lit_gpt/lora.py
- tests/test_lora.py
Hi there 👋 
This is a continuation of #771 but with some optimizations:
1. `bnb.functional.dequantize4bit` [always](https://github.com/TimDettmers/bitsandbytes/blob/8a45bfa51c4193e64b1de4424c9af05344f74173/bitsandbytes/nn/modules.py#L168) returns data in `float16` dtype, so if we want to sum it with the data in `bfloat16` dtype - both weights will be cast to `float32` and the resulting tensor also will have this dtype. To avoid it, the output of the dequantization function is cast to the dtype of the second term of the summation. This is similar to how it's [done](https://github.com/TimDettmers/bitsandbytes/blob/8a45bfa51c4193e64b1de4424c9af05344f74173/bitsandbytes/autograd/_functions.py#L516) in BNB.
2. There is no need to move the data to CPU first in order to then quantize the data …
> LoRA merge with quantization: optimiziations

- generate/sequentially.py
CUDAAccelerator.parse_devices returns a list such as ["0", "1", "2", "3"]. The count of devices is the length of the list and not the sum of the values within the list.
> Fix logic to count devices

- lit_gpt/adapter_v2.py
- lit_gpt/lora.py
- tests/test_adapter_v2.py
- tests/test_full.py
- tests/test_generate_sequentially.py
- tests/test_lora.py
Hi there 👋 
Fixes #849 
Due to a typo in `lit_gpt/adapter_v2.py` and `lit_gpt/lora.py`,  `LLaMAMoE` class inherited `LLaMAMLP`.
Thus, when trying to fine-tune Mixtral model with one of these method, you get:
```python
AttributeError: 'LLaMAMoE' object has no attribute 'fc_1'
```
This PR fixes it and adds tests to make sure that forward pass runs without issues for Mixtral model (or any other that uses mixture of experts).
> Mixtral: LLaMAMoE wrongly inherited from base LLaMAMLP for Adapter_v2 and LoRA

- generate/sequentially.py
- generate/tp.py
- lit_gpt/model.py
- tests/test_full.py
- tests/test_generate_sequentially.py
- tests/test_generate_tp.py
- tutorials/inference.md
TODOs:
Blocked by a DTensor `NotImplementedError`. Follow-up with their team.
Probably not worth since it wouldn't be straightforward to include quantization support
~~Blocked by an Inductor `NameError`. Try different nightly?~~
Blocked by Fabric change: https://github.com/Lightning-AI/pytorch-lightning/pull/19184
Simple script to check whether the model will fit:
```python
from lit_gpt import GPT
import torch
dtype = torch.bfloat16
torch.set_default_dtype(dtype)
with torch.device("meta"):
model = GPT.from_name("Llama-2-70b-chat-hf")
mlp_params = sum(p.numel() for b in model.transformer.h for p in b.mlp.parameters())
print("MLP", mlp_params * dtype.itemsize / 1e9)
qkv_params = sum(p.numel() for b in model.transformer.h for p in b.attn.attn.parameters())
print("QKV", qkv_params * …
```
> Tensor-parallel generation on multiple devices

- pretrain/openwebtext.py
- pretrain/openwebtext_trainer.py
- pretrain/redpajama.py
- pretrain/tinyllama.py
This is a minor cosmetic refactor for how hyperparameters are used in the `get_lr` function. Previously, the function did a mix of passing a global variable as input, and binding global variables at the same time. This seemed confusing and unnecessary to me.
> Refactor `get_lr` in pretraining scripts

- lit_gpt/config.py
> Mixtral supports a fully dense context length of 32k tokens

- pretrain/tinyllama.py
- tutorials/pretrain_tinyllama.md
It looks like `precision=16-mixed` will perform better. This will result in a slightly lower MFU (55% -> 52%) and a slightly higher memory usage, but still fits well into an 8xA100.
> Switch TinyLlama pretraining back to 16-mixed

- lit_gpt/config.py
- tutorials/download_mistral.md
I wanted to use mistral_instruct_v0.2, which is an instruction-fine tuned version of mistral_instruct_v0.1, but it was not supported by "python scripts/convert_hf_checkpoint.py". I compared each details and different points of mistral_instruct_v0.1 and v0.2, but there were no different points. So I added config for v0.2. 
Fixes https://github.com/Lightning-AI/lit-gpt/issues/865
> Add config for `Mistral-7B-Instruct-v0.2`

- tutorials/download_phi.md
> Add Phi-2 dropout note

- finetune/full.py
- pretrain/tinyllama.py
- tests/test_full.py
- tutorials/finetune_full.md
The core logic for full finetuning is very similar to pretraining. The main differences are in loading the checkpoint, the data we train on, and the hyperparameters. 
In this PR, I'm porting over all the improvements made in tinyllama.py to this script. Most changes are for consistency. Notable additions are:
- Correct resuming logic for dataset
- Logging of metrics
Follow-up to #788
> Updates to full-finetune script

- lit_gpt/utils.py
- tests/test_utils.py
This adds support for setting `chunked_cross_entropy(..., ignore_index=)`. This is useful sometimes when you don't want to change your data preprocessing and only update the ignore index in the training script.
> Support passing the `ignore_index` in `chunked_cross_entropy`

- .github/azure-gpu-test.yml
- README.md
- pretrain/tinyllama.py
- requirements.txt
- setup.py
- tests/test_model.py
- tutorials/pretrain_tinyllama.md
Fixes https://github.com/Lightning-AI/lit-gpt/issues/911
Since there are no breaking changes, existing torch 2.1 environments will be able to still run without issues, but we want to suggest 2.2 going forward for Flash attention 2 and compile improvements
> Upgrade to PyTorch 2.2

- scripts/download.py
- tutorials/download_code_llama.md
- tutorials/download_dolly.md
- tutorials/download_falcon.md
- tutorials/download_freewilly_2.md
- tutorials/download_function_calling_llama_2.md
- tutorials/download_llama_2.md
- tutorials/download_longchat.md
- tutorials/download_mistral.md
- tutorials/download_openllama.md
- tutorials/download_phi.md
- tutorials/download_pythia.md
- tutorials/download_redpajama_incite.md
- tutorials/download_stablelm.md
- tutorials/download_tinyllama.md
- tutorials/download_vicuna.md
- tutorials/pretrain_redpajama.md
- tutorials/pretrain_tinyllama.md
In a studio, the time to download Phi-2 went from `1:36.53` to `1:11.80`.
In my laptop, there's no noticeable difference because it's limited by memory bandwidth. (https://github.com/huggingface/hf_transfer#disclaimer)
The `[hf_transfer]` extra is unreleased so we need to install from github for now.
> Support faster checkpoint downloads

- tutorials/pretrain_tinyllama.md
The docs was missing the `meta-llama/` subdir in some places.
> Fix Llama 2 checkpoint path references

- lit_gpt/model.py
"GPT NeoX Language Model" is not correct since we support llama and several other variants. Credit is kept directly below
> Update model.py docstring

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- lit_gpt/args.py
- pretrain/openwebtext.py
- pretrain/redpajama.py
- pretrain/tinyllama.py
- Adds `validate_args` to the finetune and pretrain scripts
- Makes all scripts use `lr_warmup_steps` instead of `lr_warmup_epochs` or `lr_warmup_iters`
- Makes all scripts use `train_data_dir` and `val_data_dir` instead of `data_dir`
- Merges `OptimizationArgs` and `DataArgs` into `TrainArgs`
> Args everywhere: input validation and some standardization

- scripts/prepare_lima.py
This updates the token authentication in the LIMA data preparation script:
> FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
> Replace deprecated use_auth_token

- eval/lm_eval_harness.py
- tests/test_lm_eval_harness.py
Bug: You run the eval harness for 45 minutes just for it to fail saving the results because the directory does not exist. This PR fixes that.
> Create the directory before saving the results file in eval harness

- tests/test_adapter.py
- tests/test_adapter_v2.py
- tests/test_lora.py
These xfails were added because `bitsandbytes` can be installed on devices that don't support these kernels (aka my laptop), but I'm afraid this might silently introduce issues into our CI
> Remove bitsandbytes xfails

- tests/test_model.py
Hi there 👋 
There is a problem with importing files from `reference_model` folder.
Since this issue can plague all the newest PRs, I decided to create a separate one with the fix.
> Fix relative import in tests

- config_hub/pretrain/debug.yaml
- config_hub/pretrain/tinyllama.yaml
- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- lit_gpt/args.py
- pretrain/pretrain.py
- tests/test_adapter.py
- tests/test_adapter_v2.py
- tests/test_full.py
- tests/test_lora.py
- tests/test_pretrain.py
- tutorials/convert_lit_models.md
- tutorials/finetune_adapter.md
- tutorials/finetune_full.md
- tutorials/finetune_lora.md
- tutorials/prepare_dataset.md
A couple of improvements to args in scripts:
Removed IOArgs. Was originally used to group data args, but they have moved out. Checkpoint dir is not used by all scripts, and out dir requires to be defined dynamically for some scripts.
Alternatively, `out_dir` could also be defined under TrainArgs.
> Refactor Data - Args Improvements

- lit_gpt/adapter_v2.py
- lit_gpt/config.py
- lit_gpt/lora.py
- scripts/convert_hf_checkpoint.py
- scripts/convert_lit_checkpoint.py
- tests/test_config.py
- tests/test_lora.py
Fixes #979
This is a breaking change, so I also included removal for some legacy args. Checkpoint configs will need to be regenerated. I believe this is okay since everything has changed anyways
> Avoid underscores for config args

- lit_gpt/model.py
- tests/test_model.py
If FSDP didn't move the entire module to the device after materializing, this would get created on CPU
> Reuse `cos.device` in `reset_parameters`

- scripts/convert_lit_checkpoint.py
- tutorials/convert_lit_models.md
This was missing a `mkdir out/hf-tinyllama` to make the code fully reproducible
> mkdir in convert_lit_checkpoint

- lit_gpt/config.py
- lit_gpt/model.py
- tests/test_convert_lit_checkpoint.py
- tests/test_model.py
Hi there 👋 
Fixes #999
As @carmocca found out, the original Keras implementation of Gemma used `tanh` approximation for GeLU activation, but neither PyTorch implementation nor HF Transformers variant had it.
Recently the official PyTorch variant was [updated](https://github.com/google/gemma_pytorch/commit/324cb185aa3fe60f43dad4b7ce5096ffdd513cb1) to also use this approximation and this PR reflects this change.
> GemmaMLP uses 'tanh` approximation for GeLU activation

- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- lit_gpt/pretrain.py
- lit_gpt/utils.py
- tests/test_adapter.py
- tests/test_adapter_v2.py
- tests/test_full.py
- tests/test_lora.py
- tests/test_pretrain.py
- tests/test_utils.py
Saves a hyperparameters.yaml file to the checkpoint. Feel free to discuss the naming on this PR.
This will also be used to store the prompt template so that it can be dynamically loaded from the checkpoint after finetuning.
Part of #1005
> Save the hyperparameters to the checkpoint

- chat/base.py
- finetune/adapter.py
- finetune/adapter_v2.py
- finetune/full.py
- finetune/lora.py
- generate/adapter.py
- generate/adapter_v2.py
- generate/base.py
- generate/full.py
- generate/lora.py
- lit_gpt/prompts.py
- tests/test_adapter.py
- tests/test_adapter_v2.py
- tests/test_full.py
- tests/test_lora.py
- tests/test_prompts.py
Fixes #969
Fixes #954
Fixes #825
After this PR, you will be able to finetune
```
python finetune/full.py --config ...
```
and directly use the checkpoint:
```
python chat/base.py --checkpoint_dir out/finetune/full/final
```
Now you actually get the correct prompt style that you used for finetuning (e.g. Alpaca). On main, it does not apply the prompt style, you had to hard code it into chat.py, generate.py etc. if you wanted to use your checkpoint in Lit-GPT.
> Save and load prompt style automatically

- litgpt/data/json.py
- tests/data/test_json.py
- tutorials/prepare_dataset.md
> Enable loading train and val split in JSON data module

- litgpt/finetune/full.py
- litgpt/finetune/lora.py
- litgpt/pretrain.py
- litgpt/utils.py
- tests/test_full.py
- tests/test_lora.py
- tests/test_pretrain.py
- tests/test_utils.py
- tutorials/pretrain_tinyllama.md
I'm going for a simple `--logger_name` argument here for simplicity. We could also do the complete typing thing where we expose the specific class and then the user could set all the thousands of parameters via config file, but this seems overly complicated for now. If we later decide we want a full experiment managing, we can always go make it more into a fully fledged Trainer.
Fixes #1049
> Make logger configurable

- config_hub/finetune/llama-2-7b/full.yaml
- config_hub/finetune/llama-2-7b/lora.yaml
- config_hub/finetune/tiny-llama/lora.yaml
- litgpt/data/alpaca.py
- litgpt/data/base.py
- litgpt/data/deita.py
- litgpt/data/dolly.py
- litgpt/data/flan.py
- litgpt/data/json.py
- litgpt/data/lima.py
- litgpt/data/longform.py
- litgpt/utils.py
- tests/test_utils.py
- tutorials/prepare_dataset.md
- xla/scripts/prepare_alpaca.py
PyTorch's default `ignore_index` value is -100: https://pytorch.org/docs/stable/generated/torch.nn.functional.cross_entropy.html
I don't know if there's a reason for having a different default. Maybe we just copied this from https://github.com/karpathy/nanoGPT/blob/325be85d9be8c81b436728a420e85796c57dba7e/model.py#L187
But matching the default value can enable lowering to faster kernels that don't implement support for values different than -100. For example https://github.com/unslothai/unsloth/blob/a0cc0d163843a403a23e5cd94d20121690bd6830/unsloth/kernels/cross_entropy_loss.py#L65 or https://github.com/NVIDIA/apex/blob/b496d85fb88a801d8e680872a12822de310951fd/apex/contrib/csrc/xentropy/xentropy_kernel.cu#L703
> Match the default ignore index to PyTorch's

- pyproject.toml
After https://github.com/Lightning-AI/litgpt/pull/1080, we don't have a tutorial where we recommend installing `huggingface_hub`. So I should add it as a requirement.
> Add huggingface_hub as an 'all' dependency

- litgpt/finetune/full.py
- litgpt/finetune/lora.py
My suggestion in https://github.com/Lightning-AI/litgpt/pull/1055 was missed. We can't log "n/a" as a scalar. Also, the val loss is already logged, we don't need to log it twice.
> Fix logging of val loss

- litgpt/utils.py
- tests/test_utils.py
> Fix `save_hyperparameters()` for top-level CLI

- pyproject.toml
- tests/test_ci.py
- tests/test_lora.py
This is the commit before https://github.com/Lightning-AI/pytorch-lightning/pull/19520
There are some issues with upgrading bitsandbytes. We currently pin 0.41.0. https://github.com/Lightning-AI/litgpt/pull/946 Attempts to upgrade it.
0.42.0 fails with:
```python
/__w/7/s/tests/test_lora.py:693: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.10/dist-packages/torch/serialization.py:998: in load
with _open_file_like(f, 'rb') as opened_file:
/usr/local/lib/python3.10/dist-packages/torch/serialization.py:445: in _open_file_like
return _open_file(name_or_buffer, mode)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <torch.serialization._open_file object at 0x7f1180ba65f0>
name = …
```
> Downgrade ligthning to before bitsandbytes upgrade

- litgpt/data/__init__.py
- litgpt/data/alpaca.py
- litgpt/data/base.py
- litgpt/data/deita.py
- litgpt/data/flan.py
- litgpt/data/json_data.py
- litgpt/data/lima.py
- litgpt/data/lit_data.py
- litgpt/data/longform.py
- litgpt/data/openwebtext.py
- litgpt/data/tinyllama.py
- litgpt/data/tinystories.py
- litgpt/finetune/adapter.py
- litgpt/finetune/adapter_v2.py
- litgpt/finetune/full.py
- litgpt/finetune/lora.py
- litgpt/pretrain.py
- tests/data/test_lit_data.py
- tutorials/prepare_dataset.md
Adds a datamodule that streams data using LitData's StreamingDataset of an already preprocessed dataset. 
Example:
```py
from litgpt.data import LitData
LitData(data_path="s3://mydataset")
LitData(data_path="s3://mydataset", split_names=("train", "validation"))
```
In this PR, I'm also renaming `LitDataModule` as I found it could be confused to be related to LitData itself, which it isn't.
> Add general purpose LitData streaming data module

- config_hub/pretrain/debug.yaml
- config_hub/pretrain/tinyllama.yaml
- config_hub/pretrain/tinystories.yaml
- litgpt/pretrain.py
- tests/test_pretrain.py
Adds a new argument `litgpt pretrain --initial_checkpoint_dir` to be able to start training from an initial base checkpoint for continued pretraining. There might be a better name out there for this, suggestions welcome.
The given base checkpoint is expected to be a simple state-dict checkpoint as downloaded using `litgpt download`. The `--resume` is meant to be used to resume from checkpoints produced during pretraining (includes optimizer states and other metadata).
An alternative approach would be to not introduce a new argument and reuse `--resume` for the same functionality. However, we would need a way to detect what type of checkpoint it is and load accordingly.
> Enable continued pretraining

- config_hub/finetune/README.md
- config_hub/finetune/tiny-llama/lora.yaml
- config_hub/finetune/tiny-llama/qlora.yaml
This enables LoRA for more layers in the TinyLlama configs.
> Enable LoRA for all linear layers in tinyllama

- litgpt/pretrain.py
I found a nasty race condition when you access `len(dataloader)` in the pretraining script.
Doesn't happen on single GPU, and is rare on multi-GPU. Found on 8xH100 very it is very likely to happen due to 8 GPUs. Also only happens when the /cache dir is empty and it's downloading chunks for the first time.
In this PR rewrote the validation loop so that it doesn't access `len(datalaoder)`. After this fix, I will work on a minimal repro for litdata to investigate.
> Fix race condition when accessing `len(dataloader)` from LitData

- tutorials/convert_lit_models.md
This adds a short section to explain the steps needed when one wants to use the original evaluation harness.
> Extend Lit conversion docs

- config_hub/finetune/README.md
- config_hub/finetune/llama-2-7b/full.yaml
Note that I had to run the full finetuning on the A100's due to the peak memory requirements. Also, finetuning for only 1 epoch results in a better performance due to overfitting after epoch 1.
> Add llama 2 config entries

- config_hub/finetune/README.md
- config_hub/finetune/falcon-7b/lora.yaml
- config_hub/finetune/falcon-7b/qlora.yaml
- config_hub/finetune/mistral-7b/lora.yaml
- config_hub/finetune/mistral-7b/qlora.yaml
- config_hub/finetune/stablelm-base-alpha-3b/full.yaml
- config_hub/finetune/stablelm-base-alpha-3b/lora.yaml
- config_hub/finetune/stablelm-base-alpha-3b/qlora.yaml
Note that the 2xA10G one for StableLM is a bit slow. Maybe an issue with the machine. I could try on the A100s next week. (I couldn't run the full finetuning for the 7B models on the A10Gs so there are no checkpoints for them, yet. Will do that also on the A100 machine.)
> Add configs for falcon, mistral, stablelm

- README.md
- litgpt/pretrain.py
Enables meta device initialization and patches the `reset_parameter()` methods on the modules that require special initialization. 
Fixes #1131
In order to verify that my changes are correct and lead to the same initialization as before, I did a statistical test by comparing the weight distribution in a model using the old vs. the new implementation:
```py
import scipy.stats as stats
fabric.seed_everything(seed)
with fabric.init_module(empty_init=True):
model1 = GPT(config)
prepare_weight_initialization(model1, n_layer=config.n_layer, n_embd=config.n_embd)
model1 = fabric.setup(model1)
fabric.save("model1.ckpt", {"model": model1})
fabric.seed_everything(seed)
with fabric.init_module(empty_init=False):
model2 = GPT(config)
model2.apply(partial(init_weights, n_layer=config.n_layer, …
```
> Update weight initialization logic for faster init in pretrain

- .github/azure-gpu-test.yml
- .github/workflows/cpu-tests.yml
- pyproject.toml
Otherwise we cannot publish on PyPI.
lm_eval is a problem because it's not on PyPI
> No GitHub dependencies

- pyproject.toml
We need to add safetensors to the requirements for downloading models such as phi-2
> Add safetensors to requirements

- litgpt/scripts/convert_hf_checkpoint.py
Suppose a new user runs `litgpt download` ... They won't necessarily know where the model files are saved, and they might have to go to the docs or read the `--help` outputs to find out:
```
...
Loading 'gpt_neox.layers.4.mlp.dense_h_to_4h.bias' into RAM
Loading 'gpt_neox.layers.4.mlp.dense_4h_to_h.weight' into RAM
Loading 'gpt_neox.layers.4.mlp.dense_4h_to_h.bias' into RAM
Loading 'gpt_neox.layers.5.input_layernorm.weight' into RAM
Loading 'gpt_neox.layers.5.input_layernorm.bias' into RAM
Loading 'gpt_neox.layers.5.post_attention_layernorm.weight' into RAM
Loading 'gpt_neox.layers.5.post_attention_layernorm.bias' into RAM
Loading 'gpt_neox.layers.5.attention.query_key_value.weight' into RAM
Loading 'gpt_neox.layers.5.attention.query_key_value.bias' into RAM
Loading …
```
> Print conversion target dir

- litgpt/pretrain.py
- litgpt/utils.py
- tests/test_pretrain.py
The weight initialization currently only applies if FSDP is used, which is the normal use case. But for debugging and small models, it could make sense to run pretraining on a single GPU.
Fixes #1150
> Fix weight initialization for single device pretraining

- pyproject.toml
resolves pinned dependencies leaked from `lightning` package, part of https://github.com/Lightning-AI/lightning-thunder/pull/52#issuecomment-2016080745
> bump: `lightning ==2.3.0.dev20240324`

- litgpt/adapter_v2.py
- litgpt/lora.py
- tests/test_adapter_v2.py
- tests/test_lora.py
Hi there 👋 
In #1004 I added GeLU approximation only to the base implementation and totally forgot about LoRA and AdapterV2 variants.
In added tests there is a `pytest.mark.xfail` because I couldn't fine the reason, at least for now.
When I moved all the tests from `tests/test_model.py` into LoRA and AdapterV2 tests (and replaced base GPT with the corresponding variant) all the tests passed, except for Gemma.
Later I'll come back to the test, most likely after #1031.
> GemmaMLP: add missing approximation for LoRA and AdapterV2 variants

- .github/workflows/cpu-tests.yml
- litgpt/adapter_v2.py
Hi there 👋 
This PR adds missing `chunked_cross_entropy` for the AdapterV2.
Chunked CrossEntropyLoss was added in #178 with a goal of lowering peak memory consumption during the backward pass for PEFT applications.
For a regular fine-tuning/pre-training this isn't required since VRAM usage caused by CrossEntropyLoss will be dwarfed by all other ops.
> Chunked CrossEntropyLoss for AdapterV2

- litgpt/adapter.py
- litgpt/lora.py
- tests/test_adapter.py
- tests/test_adapter_v2.py
- tests/test_lora.py
Hi there 👋 
Apparently I forgot one more thing: WTE scaling in Adapter and LoRA variants for Gemma model.
That explain why when I did fine-tuning with 2b model the loss started from ~12 (in contrast to ~2 after the fix) and why tests failed.
> Gemma: WTE scaling for Adapter and LoRA

- litgpt/adapter_v2.py
- litgpt/lora.py
- tests/test_lora.py
Hi there 👋 
This PR fixes an issue with Gemma 7B variant and LoRA. The problem is that for the 7B variant `n_emd` != `head_size` * `n_head` and thus that caused an error when calculating the shape for `lora_B`.
Fixes #1124
> Gemma 7B x LoRA fix

- config_hub/pretrain/debug.yaml
Fixes https://github.com/Lightning-AI/litgpt/issues/1082#issuecomment-1989561205
> Use tinystories in `pretrain/debug.yaml`

- extensions/thunder/strategies/thunder_ddp.py
- extensions/thunder/strategies/thunder_fsdp.py
- tests/test_thunder_ddp.py
- tests/test_thunder_fsdp.py
Adds support for:
```python
fabric = Fabric(strategy=ThunderFSDPStrategy())
model = MyModel()
model = thunder.jit(model)
model = fabric.setup(model)  # this is now smart enough to know that model was already jitted
```
```python
import os
import thunder
import torch
import torch.distributed as torch_dist
world_size = int(os.environ.get("WORLD_SIZE", 1))
local_rank = int(os.environ.get("LOCAL_RANK", 0))
global_rank = int(os.environ.get("RANK", 0))
if world_size > 1:
torch_dist.init_process_group(backend="nccl")
pg = torch_dist.distributed_c10d._get_default_group()
device = torch.device("cuda", local_rank)
torch.cuda.set_device(device)
model = torch.nn.Linear(5, 10, bias=False, device=device)
x = torch.randn(2, 5, device=device)
def fwd_loss(m, x):
return m(x).sum()
model = …
```
> Smarter `thunder.jit` decisions

- config_hub/finetune/README.md
- config_hub/finetune/mistral-7b-v0.2/lora.yaml
- config_hub/finetune/mistral-7b-v0.2/qlora.yaml
- litgpt/config.py
- tutorials/download_model_weights.md
Not sure of MistralAI is ever going to add them to their own Hub account, but unsloth has them, so I'd say let's just add those as they work fine. We can always swap them one day if necessary.
Closes #1183
> Add mistral 7b 0.2 checkpoint

- extensions/xla/README.md
- tutorials/0_to_litgpt.md
- tutorials/inference.md
- tutorials/oom.md
- tutorials/prepare_dataset.md
Hi there 👋 
As it turned out, VSCode has built-in feature to [validate](https://code.visualstudio.com/docs/languages/markdown#_link-validation) local links in markdown files.
So after I checked all the `.md` files, I found a few “dead” links.
> Fix unreachable links in markdown files

- litgpt/finetune/adapter.py
- litgpt/finetune/adapter_v2.py
- litgpt/finetune/full.py
- litgpt/finetune/lora.py
I was going through old issues, and we discussed lowering the micro batch size to 1 a while back in #678 to make the finetuning defaults more compatible with more models and GPUs out there. This will of course increase the runtime, but given that VRAM is usually the bigger bottleneck, I think it's a worthwhile change. Especially now that we have the config files in the `config_hub`, we also have good recommendations for hparams that work well for specific models so I think lowering resource needs is maybe preferred here.
Fixes #678
> Reduce microbatch size

- README.md
- tutorials/0_to_litgpt.md
- tutorials/pretrain.md
- tutorials/pretrain_tinyllama.md
I'm finally tackling the pretraining docs we discussed in #1082
TODOs:
> Pretraining docs

- litgpt/data/json_data.py
- tests/data/test_json.py
Fixes an issue when you forget to set the `val_split_fraction`. It is optional normally in case the path is a directory with splits. But when the path is a file, it must be set because LitGPT does not support training without validation.
> Fix NoneType error when reading custom data from a JSON file

- tutorials/prepare_dataset.md
There was an extra whitespace that shouldn't have been there.
> Remove weird whitespace in docs

- litgpt/scripts/merge_lora.py
This partially reverts #1189 which added `assign=True`. The problem is that the base model checkpoints come in a different precision than what we use for finetuning. So if the LoRA weights are stored in bfloat16, but the pretrained weights are stored in float16, we get errors because with assign we don't copy/cast the tensors to the same dtype:
```
⚡ ~ litgpt merge_lora --checkpoint_dir out/qlora-llama2-7b/final 
File "/home/zeus/miniconda3/envs/cloudspace/bin/litgpt", line 8, in <module>
sys.exit(main())
File "/teamspace/studios/this_studio/llm-finetune/litgpt/litgpt/__main__.py", line 129, in main
fn(**kwargs)
File "/teamspace/studios/this_studio/llm-finetune/litgpt/litgpt/scripts/merge_lora.py", line 56, in merge_lora
merge_lora_weights(model)
File …
```
> Fix dtype mismatch when merging LoRA checkpoints

- tests/test_merge_lora.py
Adds a test that would have failed before https://github.com/Lightning-AI/litgpt/pull/1246
And aims to make sure that https://github.com/Lightning-AI/litgpt/pull/1250 and https://github.com/Lightning-AI/litgpt/pull/1248 are valid alternatives to reverting the `assign=True` change (acts as a test for both PRs)
> Parametrize merge_lora test with different dtypes

- extensions/thunder/pretrain.py
- litgpt/pretrain.py
- tests/test_pretrain.py
Saves the checkpoint at the end of training. Useful when you need to train to a fixed target of tokens/steps. Ports changes from continued pretraining studio.
> Save checkpoint at the end of training

- litgpt/chat/base.py
- tests/test_chat.py
fix  using chat with lora checkpoints.
> Fix chat with LoRA

- README.md
This replaces Alpaca with a "custom" dataset upon request. Custom in a sense that it shows that a user could bring their own files given that they formatted correctly. The model trains well here with default settings:
```bash
Epoch 1 | iter 1 step 0 | loss train: 3.136, val: n/a | iter time: 366.52 ms
Epoch 1 | iter 2 step 0 | loss train: 3.313, val: n/a | iter time: 128.25 ms
Epoch 1 | iter 3 step 0 | loss train: 3.208, val: n/a | iter time: 125.93 ms
Epoch 1 | iter 4 step 0 | loss train: 3.239, val: n/a | iter time: 125.72 ms
Epoch 1 | iter 5 step 0 | loss train: 3.261, val: n/a | iter time: 134.85 ms
Epoch 1 | iter 6 step 0 | loss train: 3.133, val: n/a | iter time: 132.94 ms
Epoch 1 | iter 7 step 0 | loss train: 3.167, val: n/a | iter time: 123.77 ms
Epoch 1 | iter 8 step 0 | loss …
```
> Custom dataset for finetuning snippet

- tutorials/prepare_dataset.md
Looks like the JSON data approach requires specifying `--val_split_fraction`. Just added this to the example.
> Update prepare_dataset.md to add required val_split_fraction to JSON approach

- .github/workflows/cpu-tests.yml
- README.md
- litgpt/config.py
- litgpt/prompts.py
- tutorials/download_model_weights.md
Hi there 👋 
Google released three variants of Gemma model for code generation: `2b`, `7b` and `7b-it`
`2b` and `7b` variants are useful only for code completion, they require a special prompt and the output is not the best (see examples [here](https://github.com/Lightning-AI/litgpt/issues/1270#issuecomment-2049665751)).
`7b-it` is a much better model, more versatile and generates plausible outputs.
Thus this PR adds only this model.
---
If there is a strong intent to also include `2b` and `7b` variants, I recommend to first add support for a custom prompt (provided as an argument).
> CodeGemma-7b-it

- extensions/thunder/pretrain.py
- litgpt/pretrain.py
- litgpt/utils.py
- tests/test_utils.py
In the previous version of LitGPT, I added this code to sanitize the hparams for logging:
https://github.com/Lightning-AI/litgpt/blob/8a101b633dfeafd378f8fbaba6a80a4417c33576/pretrain/tinyllama.py#L65
But this code was removed in the new version, causing errors like:
```
TypeError: Object of type PosixPath is not JSON serializable
```
(e.g. with wandb)
I plan to improve this in Lightning's `.log_hyperparameters()` implementation, after which we can remove the function I added here again.
> Fix capturing hparams for loggers that don't support serializing non-primitives

- litgpt/prompts.py
In `generate/base.py`, the output is 
```
Instruct:Fix typos in the following sentence: Exampel input
Output: Example input.
```
which looks a bit ugly.
> Add whitespace after "Instruct:"

- README.md
Adds examples for pretraining custom datasets to the Readme as requested.
> Custom datasets examples for pretraining and continued pretraining

- README.md
Fixes the badge (yes, badge not batch size :D).
Before:
After:
> Fix badge size

- README.md
> Add Pre-training Small Base LMs with Fewer Tokens paper to community projects

- litgpt/data/tinystories.py
- litgpt/eval/evaluate.py
- litgpt/prompts.py
- litgpt/scripts/convert_hf_checkpoint.py
- litgpt/scripts/merge_lora.py
- litgpt/tokenizer.py
- litgpt/utils.py
- tests/data/test_tinystories.py
- tests/test_config.py
- tests/test_convert_lit_checkpoint.py
- tests/test_evaluate.py
- tests/test_merge_lora.py
- tests/test_prompts.py
- tests/test_utils.py
Hi there 👋 
One might ask why do we need to specify encoding explicitly, when it should be by default `utf-8`.
Well, not quite.
> The default encoding is platform dependent (whatever locale.getpreferredencoding() returns)
Which means that on Windows we can have an error, and that is exactly what recently [happened](https://github.com/Lightning-AI/litgpt/actions/runs/8654742013/job/23751422665#step:7:1110).
> Specify `UTF-8` encoding for every `open` function

- .github/workflows/check-links.yml
This hyperlink checker is a bit more reliable than the previous one, also checks jupyter notebooks, rst, and html files in addition to markdown, and also has a pytest-style output that is easier to read.
> Improved link checker

- tests/test_thunder_fsdp.py
This PR skips `test_save_load_sharded_checkpoint` in order to unblock CI.
Opened #1303 to look into making the test faster.
> Temporarily skip thunder test due to timeout

- .github/workflows/check-links.yml
The intention for this was mainly to check for broken internal links. External links can sometimes time out or be subject to GitHub rate limiting, so let's ignore those.
> ignore external links

- tests/test_tokenizer.py
Hi there 👋 
`test_tokenizer_against_hf` might be flaky due to connection issues.
This PR adds a decorator that reruns the test in case of a failure for a total of 5 attempts.
> Rerun test_tokenizer on fail

- README.md
- litgpt/__main__.py
- litgpt/deploy/serve.py
- pyproject.toml
- tests/test_cli.py
- tests/test_serve.py
- tutorials/0_to_litgpt.md
- tutorials/deploy.md
The LitGPT serve API. E.g., use as
```bash
litgpt serve --checkpoint_dir checkpoints/microsoft/phi-2
```
and then send requests via 
```
In [1]:  import requests, json
In [2]:  response = requests.post(
...:      "http://127.0.0.1:8000/predict",
...:          json={"prompt": "Fix typos in the following sentence: Exampel input"}
...:          )
```
> Litgpt serve API

- README.md
- litgpt/__main__.py
- tests/test_cli.py
This PR is a hack to add a default for the `litgpt finetune` command as a short-term solution. The default was chosen to be lora. In other words
```
litgpt finetune [args]
```
is now equivalent to
```
litgpt finetune lora [args]
```
and the other subcommands still exist.
> Rewrite finetune command if subcommand is not provided

- litgpt/config.py
Sets the context size for Llama3.
The model card reports it is 8k. I guess it is probably a power of 2.
https://huggingface.co/meta-llama/Meta-Llama-3-70B
Thanks @IvanYashchuk
> Set the context size for LLama3

- litgpt/finetune/adapter.py
- litgpt/finetune/adapter_v2.py
- litgpt/finetune/full.py
- litgpt/finetune/lora.py
- litgpt/pretrain.py
- litgpt/utils.py
- tests/test_pretrain.py
- tests/test_utils.py
Apply the `init_out_dir(out_dir)` used for pretraining also to the finetuning scripts.
Fixes #1312
> Standardize out_dir behavior

- litgpt/eval/evaluate.py
- tests/test_evaluate.py
The command we have in the docs fails:
```
litgpt evaluate \
--checkpoint_dir checkpoints/microsoft/phi-2/ \
--batch_size 16 \
--tasks "hellaswag" \
--out_dir evaluate_model
```
```
File "/home/zeus/miniconda3/envs/cloudspace/bin/litgpt", line 8, in <module>
sys.exit(main())
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/__main__.py", line 143, in main
fn(**kwargs)
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/litgpt/eval/evaluate.py", line 99, in convert_and_evaluate
model = HFLM(repo_id, state_dict=state_dict, device=device, batch_size=batch_size, dtype=dtype)
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lm_eval/models/huggingface.py", line 143, in __init__
assert …
```
> Fix evaluation if device not specified

- litgpt/deploy/serve.py
- pyproject.toml
Updates the hardcoded "cuda" to "auto"
> Use new litserve accelerator="auto" setting

- litgpt/eval/evaluate.py
- litgpt/utils.py
- tests/test_evaluate.py
Fixes #1349
I found that the `litgpt evaluate` command ignores the provided checkpoint dir and *silently* downloads the model from HF. Since the download speeds in Studios is so fast, I didn't notice this. The only hint that this is happening is when I saw #1349 but I interpreted this first as it just wanting to download a missing config file. Later when I looked at the benchmark numbers and saw that LoRA, QLoRA and full finetuning returned all had the same eval benchmark numbers, I was led down this rabbit hole.
The fix is to correctly pass the pretrained checkpoint file to the HFLM class. 
Tied to this is the problem that the huggingface state dict loader forces `weights_only=True`, which our checkpoints don't support because they are saved using pickle in the incremental saver. So I …
> Fix `litgpt evaluate` not using the local checkpoint

- config_hub/finetune/README.md
It was requested that I publish the Studio that was used to generate the numbers in our table. 
This PR adds a link to it in the text.
> Add link to Studio for benchmarks

- README.md
Mistral 7B instruct recently became gated, so let's use phi-2 for now for the examples in the Readme.
> Change examples to phi-2

- tests/test_lora.py
#1374 changed the assertion but it's not needed. The values are exactly equal. Also the function used there is deprecated in PyTorch.
> Update LoRA test

- litgpt/scripts/download.py
This adds more informative error messages for the various access token issues to address #1363.
Also, I tried to reduce the stack trace @lantiga . Instead of 
```
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
response.raise_for_status()
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/meta-llama/llama-2-7b
The above exception was the direct cause of the following exception:
File …
```
> More informative download error messages

- tests/test_model.py
Fixes https://github.com/Lightning-AI/litgpt/pull/1282#discussion_r1590758153
The existing test is `test_against_hf_mistral`
> Remove duplicate MistralForCausalLM test

- tests/test_lora.py
Hi there 👋 
As @awaelchli [suggested](https://github.com/Lightning-AI/litgpt/pull/770#discussion_r1591600891), this PR extends the test for LoRA to make sure that all the tensors (parameters, buffers, attributes) are materialized.
With just a forward pass we depend on the config: if LoRA is applied to all matrices (Q, K and V), then we don't need `zero_pad` method during a forward pass and thus might not notice that `lora_ind` inside the method is a non-materialized tensor.
> LoRA test: check that all the tensors are materialized.

- tutorials/prepare_dataset.md
I think this is not super obvious to most people who aren't familiar with jsonargparse.
> Explain dataset options

- litgpt/data/lit_data.py
- tests/data/test_lit_data.py
The LitData class accepts a seed which is supposed to control the shuffling of the dataset. However, this seed is never passed to the StreamingDataset. As a result, it has no effect on the shuffle state.
> Fix bug where LitData doesn't use seed

- litgpt/prompts.py
The file `/litgpt/prompts.py` was missing the mapping between the `llama3` model name and the `Llama3` PromptStyle class in the variable `prompt_styles`.
> Add prompt style mapping for llama3

- litgpt/utils.py
- tests/test_utils.py
cc @rasbt 
Avoids
```python
File "/home/carlos/nightly-env/bin/litgpt", line 8, in <module>
sys.exit(main())
File "/home/carlos/lit-parrot/litgpt/__main__.py", line 150, in main
fn(**kwargs)
File "/home/carlos/lit-parrot/litgpt/pretrain.py", line 122, in setup
main(
File "/home/carlos/lit-parrot/litgpt/pretrain.py", line 179, in main
optimizer = instantiate_torch_optimizer(optimizer, model.parameters(), **extra_kwargs)
File "/home/carlos/lit-parrot/litgpt/utils.py", line 517, in instantiate_torch_optimizer
optimizer = instantiate_class(model_parameters, optimizer, **kwargs)
TypeError: instantiate_class() got an unexpected keyword argument 'fused'
```
> Fix optimizer init with fused=True

- pyproject.toml
Seems like the LitData 0.2.7 release made some changes that messes with out tests. Let's pin it to 0.2.6 until we have time to investigate what's causing the discrepancies.
> Pin litdata

- README.md
For some reason, it now looks different in the actual readme vs the previewed readme.
Preview:
Actual:
Kind of frustrating. I will try to fix it, and if doesn't work then undo it.
> Fix README.md alignment

- litgpt/utils.py
- tests/test_utils.py
This error message still referred to `--checkpoint_dir` which doesn't exist anymore as a flag. Cleaning it up.
> Update error message

- litgpt/__main__.py
I am preparing a demo, and the 
> You are using a CUDA device ('NVIDIA A10G') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
warning when using the `chat` and `generate` scripts is a bit ugly and annoying. So, I was removing it here by setting `torch.set_float32_matmul_precision("high")` if the device has tensor cores. 
Can you think of a downside/reason why we shouldn't do this @awaelchli ?
> Detect tensor cores

- litgpt/finetune/adapter.py
- litgpt/finetune/adapter_v2.py
- litgpt/finetune/full.py
- litgpt/finetune/lora.py
Fixes an issue that arises if the validation set contains examples longer than the ones in the training set as encountered in #1461
> Fix sequence length bug

- litgpt/args.py
> Add `lr_warmup_steps`, `max_steps` values validation

- litgpt/scripts/merge_lora.py
This fixes an issue where we always overwrite the provided initial checkpoint dir path with the one provided as metadata. 
CC @awaelchli 
This fixes a bug where the wrong path was used when merging the LoRA weights:
```
litgpt finetune microsoft/phi-2 \
--data JSON \
--data.json_path my_custom_dataset.json \
--data.val_split_fraction 0.0001 \
--out_dir out/phi-2-finetuned --train.max_steps 20
{'checkpoint_dir': PosixPath('checkpoints/microsoft/phi-2'),
'data': JSON(json_path=PosixPath('my_custom_dataset.json'),
mask_prompt=False,
val_split_fraction=0.0001,
prompt_style=<litgpt.prompts.Alpaca object at 0x7fd59d600e80>,
ignore_index=-100,
seed=42,
num_workers=4),
'devices': 1,
'eval': EvalArgs(interval=100,
max_new_tokens=100,
max_iters=100,
initial_validation=False),
'logger_name': 'csv', …
```
> Fix issue where path in merge_lora is overwritten

- litgpt/eval/evaluate.py
- tests/test_evaluate.py
Fixes #1467 to allow setting the `batch_size` to "auto" in `litgpt evaluate`
> Allow batch size "auto" setting in evaluate

- litgpt/eval/evaluate.py
- tests/test_evaluate.py
This addresses a limitation where `'auto:N' could not be passed as `batch_size` argument in `litgpt evaluate` mentioned in #1467
> Allow batch argument with batch recomputation

- litgpt/deploy/serve.py
- litgpt/generate/base.py
- tests/test_serve.py
- tutorials/deploy.md
The default setting in `generate/base.py` returns the formatted prompt plus response, which is useful for demonstration and seeing what's going on. However, when using the model for serving, it can lead to ugly outputs like 
```
system
You are a helpful assistant.
user
Fix typos in the following sentence: Exampel input
assistant
The corrected sentence is: "Example input".
```
So this PR fixes that and allows the `generate` function in `generate/base.py` to be consistent with the chat behavior.
CC @aniketmaurya
> Exclude prompt from generated response

- litgpt/prompts.py
- tests/test_prompts.py
This PR adds multi-turn prompt handling for Llama3 as per the official model card prompt format [here](https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/)
> add multi turn prompt

- config_hub/finetune/llama-2-7b/full.yaml
- config_hub/finetune/llama-3-8b/full.yaml
- config_hub/finetune/phi-2/full.yaml
- config_hub/pretrain/debug.yaml
- config_hub/pretrain/microllama.yaml
- config_hub/pretrain/tinyllama.yaml
- config_hub/pretrain/tinystories.yaml
- extensions/thunder/pretrain.py
- litgpt/finetune/full.py
- litgpt/pretrain.py
- litgpt/utils.py
- tests/test_utils.py
The current resuming logic allows the user to pass `--resume=True` to find the latest checkpoint in the `out_dir` folder. However, this requires the checkpoint to exist, and is safe to ensure the user loads a checkpoint when intended. However, in a job where we auto-resume, we can't set `resume=True` because an initial checkpoint never exists. This PR adds `--resume='auto'` that does the same as `--resume=True` except it won't error if no checkpoint is found.
When it's reviewed, I'll add it to the other scripts.
> Add `resume="auto"`

- pyproject.toml
This bumps the version so I can make a new release so that we can fix the NumPy 2.0 version issue (#1494) for people who install LitGPT from PyPI.
> Version bump for new release to fix NumPy issue

- litgpt/scripts/download.py
Prints a message when unneeded safetensor files can't be deleted by the `download.py` script (and issue that appears on Windows).
Fixes #1297
> Print message when unnecessary can't be deleted

- extensions/xla/generate/adapter.py
- litgpt/__init__.py
- litgpt/api.py
- litgpt/chat/base.py
- litgpt/deploy/serve.py
- litgpt/generate/adapter.py
- litgpt/generate/adapter_v2.py
- litgpt/generate/base.py
- litgpt/generate/full.py
- tests/test_api.py
- tutorials/developer-docs/python-api.md
- tutorials/python-api.md
This is a PR to implement a subset of the LitGPT Python API as discussed in #1459 (CC @aniketmaurya). This subset will focus only on the inference aspects (not the training and finetuning, yet).
To get the v1 out for inference soon, and to lower the reviewer burden for a single PR, these features will be added in separate PRs:
- Add streaming option
- Add functionality to download the model automatically
- Add multi-GPU loading
- Add finetuning functions
- Add pretraining function
- Extend to multi-device inference
> LitGPT Python API v1

- .github/workflows/cpu-tests.yml
There are some issues with upgrading pip in the Windows CI. Trying to fix it.
```
Run pip install --upgrade pip
Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages (24.0)
Collecting pip
Downloading pip-24.1-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.1-py3-none-any.whl (1.8 MB)
---------------------------------------- 1.8/1.8 MB 29.2 MB/s eta 0:00:00
ERROR: To modify pip, please run the following command:
C:\hostedtoolcache\windows\Python\3.10.11\x64\python.exe -m pip install --upgrade pip
```
> Fix pip upgrade command on windows

- litgpt/api.py
- tutorials/python-api.md
Changes the suggested import from 
```
```
to
```
from litgpt import LLM
```
Also, it makes the response consistent whether stream is selected or not. That means, the input tokens are not prepended to the returned output (if someone wants that, it's easy to do manually)
> Update LLM import and make stream/non-stream option consistent

- litgpt/api.py
- tests/test_api.py
- tutorials/python-api.md
Adds an option to download the checkpoint from the hub:
```
from litgpt import LLM
llm = LLM.load("microsoft/phi-2", accelerator="cuda", init="hub")
```
In a future PR, we can add support for `init="auto"` where we check if the local path contains a checkpoint, and if not, then download.
Or maybe we should do this already here and skip the download if the path exists ...
> Add Python API download option

- extensions/thunder/unsloth/kernels/rope_embedding.py
This is an attempt to fix one of the Thunder tests due to the new stricter triton in the latest PyTorch nightly: https://dev.azure.com/Lightning-AI/lit%20Models/_build/results?buildId=206391&view=logs&j=05e5d4de-bf1b-5a1e-701d-c4191065dd60&t=014e096d-69a7-571e-fca7-00c9b59c1724
> Add Rope group size as constexpr to fix thunder tests

- litgpt/api.py
- litgpt/utils.py
- tests/test_api.py
- tutorials/python-api.md
Adds the following behavior
```python
LLM(model="microsoft/phi-2", init="random")
```
```python
LLM(model="microsoft/phi-2")
```
Same as above, if model exists via the "microsoft/phi-2" path:
```python
LLM(model="microsoft/phi-2")
```
```python
LLM(model="microsoft/phi-2", init="local")
```
CC @lantiga @williamFalcon
> Add automatic checkpoint downloading in Python API

- litgpt/tokenizer.py
- tests/test_tokenizer.py
Hi there 👋 
This PR changes the default tokenizer from SentencePiece to Tokenizers by HF.
There are mainly three reasons why it's a good idea:
1. Tokenizers library is faster* than SentencePiece
2. Easier to maintain
3. Easier to extend (if necessary)
> [!IMPORTANT]
> If a PR is created from a fork, then the `HF_TOKEN` is not shared. That means that tests for models/tokenizers from gated repos are skipped. **Before merging someone from the core team has to copy this branch to a new one, create a PR and run tests.** Like it was done in #1342.
Let's validate it with a simple benchmark:
```python
from time import perf_counter
import requests
from huggingface_hub import snapshot_download
from sentencepiece import SentencePieceProcessor
from tokenizers import Tokenizer as HFTokenizer
from …
```
> Tokenizer: prefer HF Tokenizer

- README.md
Adds `litgpt evaluate` to the Readme file.
> Add `evaluate` to Readme

- pyproject.toml
Bumps the version so we can make a release for 0.4.2 that includes the new API.
> Bump version for 0.4.2 release

- .github/workflows/publish.yaml
There's currently a build issue with Twine:
```
...
adding 'litgpt-0.4.2.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built litgpt-0.4.2.tar.gz and litgpt-0.4.2-py3-none-any.whl
File "/opt/hostedtoolcache/Python/3.12.4/x64/bin/twine", line 5, in <module>
from twine.__main__ import main
File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/twine/__init__.py", line 40, in <module>
__uri__ = metadata["home-page"]
~~~~~~~~^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
raise KeyError(item)
KeyError: 'home-page'
Error: Process completed with exit code 1.
```
See https://github.com/pypa/twine/issues/977 for details.
> Fix Twine Build Issue

- litgpt/prompts.py
Mixtral models defaulted to the Alpaca prompt style because they were never integrated into the `model_name_to_prompt_style` function. This simple regex modification fixes this.
> Fix Mixtral prompt style

- litgpt/api.py
- litgpt/chat/base.py
- litgpt/generate/adapter.py
- litgpt/generate/adapter_v2.py
- litgpt/generate/base.py
- litgpt/generate/full.py
- litgpt/utils.py
- tests/test_utils.py
Raises a warning if a user loads a model larger than TinyLlama on a CPU device for inference.
> Raise warning when loading a large model on a CPU device

- tutorials/0_to_litgpt.md
- tutorials/convert_lit_models.md
This PR provides a minor documentation fix for `convert_from_litgpt` command examples to remove the `output_dir` flag.  This flag is no longer supported by the CLI, instead the output is specified as the second position argument.
> Tutorial `convert_from_litgpt` doc fix to remove `output_dir` command argument

- litgpt/prompts.py
- tests/test_tokenizer.py
Coincidentally, after we merged the Phi-3 checkpoint, Microsoft silently made some updates to Phi-3:
This includes the prompt template, which is now 
```
<|system|>
You are a helpful assistant.<|end|>
<|user|>
hello world
<|assistant|> 
```
and the removal of the double-BOS token.
> Update phi-3 prompt template

- litgpt/scripts/convert_hf_checkpoint.py
Remove some unused code in the HF conversion code to estimate file sizes
> Remove redundant code in checkpoint conversion script

- litgpt/eval/evaluate.py
- tutorials/0_to_litgpt.md
- tutorials/deploy.md
- tutorials/evaluation.md
This updates the instruction on how users can get the task list in `litgpt evaluate`. I.e., 
```bash
litgpt evaluate list | grep mmlu
```
```
mmlu_philosophy_generative
mmlu_humanities_generative
mmlu_high_school_european_history_generative
mmlu_moral_disputes_generative
mmlu_anatomy_generative
mmlu_stem_generative
mmlu_business_ethics_generative
...
```
> Update how evaluate tasks are listed

- litgpt/tokenizer.py
- tests/test_tokenizer.py
Hi there 👋 
This PR implements @awaelchli [comment](https://github.com/Lightning-AI/litgpt/pull/1518/files#r1652216568).
Basically, it's a test to make sure that `bos` and `eos` tokens are applied w.r.t. to a provided config/args.
> Tokenizer: check that `bos` and `eos` tokens are applied w.r.t. to a provided config/args

- config_hub/finetune/README.md
- config_hub/finetune/phi-3/full.yaml
- config_hub/finetune/phi-3/lora.yaml
- config_hub/finetune/phi-3/qlora.yaml
This adds configuration files for the newly added Phi-3 model. Note that the `full` finetuning uses less memory than the LoRA one, which is interesting. The microbatch size is the same, and I also reran this 2 times to make sure.
> Add Phi-3 Configs

- litgpt/tokenizer.py
- tests/test_tokenizer.py
Hi there 👋 
When I was working on Phi-3 integration I've spotted an issue with HF Tokenizer that if to decode a single token at time (like in chat script), then it drops all the spaces and the output looks like a single looooooong string (https://github.com/huggingface/transformers/issues/31643).
So, instead of `This is a test string` the code prints `Thisisateststring`.
As was mentioned in the issue by @itazap, the problem happens with `LlamaTokenizer` and thus affects not only Phi-3, but other models too.
This PR applies the hack from Phi-3 to other models.
> Tokenizer: fix issue when decoding a single token at a time

- litgpt/prompts.py
Fixes https://github.com/Lightning-AI/litgpt/issues/1565
> Remove duplicated bos_token for CodeLlama

- litgpt/data/base.py
- tests/conftest.py
Fixes https://github.com/Lightning-AI/litgpt/issues/1567.
> Fix SFTDataset sample generation

- tutorials/0_to_litgpt.md
Adds a section to the "Zero to LitGPT: Getting Started with Pretraining, Finetuning, and Using LLMs" docs that describes the Python API
> Add Python API section to 0 to LitGPT docs

- litgpt/prompts.py
- tests/test_prompts.py
Using `.format()` may overwrite user input. Rewrote in the style of the [llama prompt format](https://github.com/meta-llama/llama3/blob/359887376f0aaf30e433f23e25df858d8c2a9833/llama/tokenizer.py#L202-L229), and removed the extra newline from the system prompt.
> Fix multi-turn prompting error handling and extra newline

- README.md
- litgpt/api.py
- litgpt/chat/base.py
- litgpt/deploy/serve.py
- litgpt/eval/evaluate.py
- litgpt/finetune/adapter.py
- litgpt/finetune/adapter_v2.py
- litgpt/finetune/full.py
- litgpt/finetune/lora.py
- litgpt/utils.py
- tests/test_chat.py
- tests/test_config_hub.py
Extends `chat`, `evaluate`, `serve`, and finetuning commands to automatically download the model if the input is a valid model repo and the checkpoint dir doesn't exist locally yet.
> Add automatic downloading to CLI

- pyproject.toml
This bumps the version so we can make a new release that includes the latest fixes and additions (like the automatic CLI downloading) that is currently used in the README.
> Bumb version for 0.4.4 release

- litgpt/scripts/download.py
- litgpt/utils.py
Resolved Issue [#1557](https://github.com/Lightning-AI/litgpt/issues/1557) posted by @Andrei-Aksionov regarding warnings from depricated codebase.
- Removed depricated params scripts/download.py
- passed Storage obj instead of ptr in utils.py
Tests:
✅ test_convert_hf_checkpoint.py
✅ test_convert_lit_checkpoint.py
✅ test_convert_pretrained_checkpoint.py
Also tested manually downloading the model for warnings.
> ✅ Issue #1557: Fixed warning during model download and conversion.

- litgpt/chat/base.py
Hi there 👋 
Inside `auto_download_checkpoint` the code also extends the path by prepending `checkpoints/` if it's not provided.
Since currently it's done after `check_file_size_on_cpu_and_warn`, the command
```bash
litgpt chat google/gemma-2-9b-it
```
will fail.
> chat/base.py: extend checkpoint_dir before accessing it

- litgpt/chat/base.py
- tests/test_chat.py
Hi there 👋 
Fixes #1558 
In the `chat` script the size of `kv-cache` is set to model's maximum context size, while in the `generate` script - as a sum of `len(prompt)` and `max_new_tokens`. That leads to unnecessary VRAM consumption and sometimes OOM errors in the chat mode, while the generate script might run fine (since kv-cache might be much smaller as it depends on max_new_tokens value).
This PR adds `max_new_tokends` argument to the chat script and sets kv-cache in the same fashion as the generate script, only for each conversation turn.
> Chat: dynamically set kv-cache size

- pyproject.toml
This increases the version number so we can make a new release that includes the KV-cache fixes and Mathstral
> Increase version number for 0.4.5 release

- litgpt/api.py
- litgpt/deploy/serve.py
I think I found the culprit causing the weird results mentioned in #1595. I think the kv-cache was cleared incompletely. I will try out some more models, but it seems to look promising so far.
Fixes  #1595
> Fix kv-cache clearing in Python API and Serve

- litgpt/api.py
The `eos_id` parameters was not used in the Python API. It can be removed because the `eos_id` is applied from the tokenizer directly. (It would be unreasonable for a user to know the `eos_id` because it's model dependent.)
> Remove non-used eos_id in Python API

- litgpt/deploy/serve.py
This fixes a high memory-usage issue in `litgpt serve` where the kv cache was always set to the maximum block size. (Analogous to #1583)
> Dynamically set kv-cache size in serve

- litgpt/data/lit_data.py
- litgpt/data/microllama.py
- litgpt/data/openwebtext.py
- litgpt/data/text_files.py
- litgpt/data/tinyllama.py
- litgpt/data/tinystories.py
- pyproject.toml
- tests/data/test_lit_data.py
- tests/data/test_textfiles.py
- tests/data/test_tinystories.py
Restores the assertions to what they were before updating LitData in https://github.com/Lightning-AI/litgpt/pull/1573. LitData 0.2.17 has fixes for handling drop_last, which was causing the previous changes in the assertions and number of samples returned. 
This also addresses the comment from @carmocca https://github.com/Lightning-AI/litgpt/pull/1573#discussion_r1675794515
> Update LitData version and restore previous LitData assertions in tests

- litgpt/api.py
Fixes a spelling issue in the API that was a leftover from a previous implementation where users specified the `max_returned_tokens` instead of `max_new_tokens`
> max_returned_tokens -> max_new_tokens

- litgpt/data/text_files.py
- tests/test_readme.py
For efficiency purposes, `litgpt pretrain` skips the expensive dataset preprocessing if it is run a second time on the same dataset folder. However, users may have changed the input text files since the last time they ran the command, which could cause issues. So in this case, there is now a warning about the skipped preprocessing and a note about how to trigger reprocessing.
Fixes #1450
> Add warning about pretrain preprocessing

- litgpt/scripts/download.py
- tests/test_readme.py
In the last few days, there were a few internal and external confusions about using unsupported models in LitGPT. Currently, LitGPT lets one download unsupported models, but then fails in the conversion. E.g.,
```
litgpt download NousResearch/Hermes-2-Pro-Llama-3-8B
...
...
File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/dist-packages/litserve/server.py", line 332, in inference_worker
lit_api.setup(device)
File "/app/server.py", line 12, in setup
self.llm = LLM.load(
File "/usr/local/lib/python3.8/dist-packages/litgpt/api.py", line 112, in load
checkpoint_dir = …
```
> Print warning about unsupported repo_ids

- litgpt/scripts/download.py
- tests/test_readme.py
This restores the capability to load custom checkpoints via the `--model_name` option, for example:
```bash
litgpt download NousResearch/Hermes-2-Pro-Llama-3-8B --model_name Llama-3-8B
```
> Restore capability to load alternative weights

- litgpt/generate/sequentially.py
- tests/test_generate_sequentially.py
Previously, running a model with a number of layers that was not evenly divisible by the number of devices used was not supported. This PR makes it possible by packing more layers on the first n-1 GPUs and allowing the last one to have fewer layers as the remainder. There will still be edge cases where we wouldn't be able to do that as the remainder could be 0, but this PR keeps it simple and excludes these cases. 
Example:
Enables running Meta-Llama-3.1-405B. It has 126 layers, which is not divisible by 8. So prior implementation couldn't distribute that. This implementation will pack ceil(126 / 8) = 16 layers on the first 7 GPUs each, and 126 - 7 * 16 = 14 layers on the last GPU. 
```
litgpt generate_sequentially checkpoints/meta-llama/Meta-Llama-3.1-405B --devices 8 --precision …
```
> Enable unbalanced number of layers in sequential generation

- pyproject.toml
Bumps version for the next release that will include Gemma 2 and Llama 3.1 support
> Bumb version to 0.4.6 for next release (Gemma 2 and Llama 3.1)

- litgpt/api.py
The docstring incorrectly said it was accepting a processed tensor as a prompt, but it should be a string.
> Fix prompt docstring in Python API

- pyproject.toml
Following up on #1494 I had a reminder for July to see if we can now remove the old NumPy version pin and support NumPy 2.0.
Fixes #1494
> Remove NumPy < 2.0 pin

- litgpt/api.py
Fixes an issue with setting the kv-cache when using the Python API when `streaming=True`:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], [line 2](vscode-notebook-cell:?execution_count=2&line=2)
[1](vscode-notebook-cell:?execution_count=2&line=1) result = llm.generate("What is 1 + 2?", stream=True)
----> [2](vscode-notebook-cell:?execution_count=2&line=2) for e in result:
[3](vscode-notebook-cell:?execution_count=2&line=3)     print(e, end="", flush=True)
File ~/litgpt2/litgpt/api.py:247, in LLM.generate.<locals>.iterator()
[245](https://vscode-remote+vscode-002d01j33eabry5h6bsyvfqn84g9rv-002estudio-002elightning-002eai.vscode-resource.vscode-cdn.net/teamspace/studios/thi …
```
> Fix kv-cache issue in Python API streaming mode

- pyproject.toml
This updates the minimal installation requirements so that basic litgpt functions like `litgpt chat microsoft/phi-2` can be used out of the box without executing
```
litgpt install "litgpt[all]"
```
We have the above installation listed in the README, but it's more intuitive for people to just use `litgpt install litgpt`, and this caused a lot of frustration for users in workshops and in general. 
Fixes #1632
> Updates installation requirements to install minimal required packages for basic use

- litgpt/scripts/download.py
Conversion of .safetensors to .bin files can take a while for models that are large because there are many such files (70B has 30 files, 405B has 119 files), but disk I/O doesn't seem to be saturated. This PR explores using a process pool to process multiple files in parallel. 
Llama 3.1 405B
Conversion completed: This PR 5.96 minutes, main branch: 22.85 minutes
Max memory: This PR 56 GB, main branch: 10 GB
> Faster safetensors conversion when downloading model

- litgpt/data/alpaca.py
- litgpt/data/deita.py
- litgpt/data/dolly.py
- litgpt/data/flan.py
- litgpt/data/json_data.py
- litgpt/data/lima.py
- litgpt/data/lit_data.py
- litgpt/data/longform.py
- litgpt/data/openwebtext.py
- litgpt/data/text_files.py
- litgpt/data/tinyllama.py
- litgpt/data/tinystories.py
- tests/data/test_alpaca.py
- tests/data/test_deita.py
- tests/data/test_dolly.py
- tests/data/test_json.py
- tests/data/test_longform.py
- tests/data/test_openwebtext.py
- tests/data/test_tinyllama.py
The LitGPT datamodules inherit from LightningDataModule, but most of them are dataclasses and we forgot to call `super().__init__()`. When attempting to use the data module with the Lightning Trainer, we get:
```
AttributeError: 'Alpaca' object has no attribute 'prepare_data_per_node'
```
This PR adds the missing super call and ensures the modules can be used with Lightning Trainer.
> Add missing super() call in data modules

- pyproject.toml
Includes the fix: https://github.com/Lightning-AI/pytorch-lightning/pull/20121 @rasbt 
There will be a 2.4 release soon.
Closes #1604 (?)
> Update Lightning version to 2.4.0 pre

- litgpt/api.py
- litgpt/model.py
- litgpt/scripts/convert_hf_checkpoint.py
- tests/test_api.py
Adds `dynamic`, `max_model_supported` and `int` modes for handling the kvcache size. This is useful for Thunder, as we do not yet support dynamic shapes.
> Add tunable kvcache with error handling for nonsense inputs.

- litgpt/deploy/serve.py
This replaces the custom code in `litgpt serve` by the Python `LLM` API. 
The goal of this is to lower maintenance and duplication efforts, because this way we don't have to apply modifications and fixes in two places separately.
> Use Python API in serve code

- litgpt/api.py
In some scenarios, no error was raised when too many tokens were requested. Or rather, it led to a cryptic error:
```
llm = LLM.load("EleutherAI/pythia-160m")
llm.generate("What do llamas eat?", max_seq_length=10)
```
```python
RuntimeError                              Traceback (most recent call last)
Cell In[5], line 1
----> 1 llm.generate("What do llamas eat?", max_seq_length=30)
File /home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
112 @functools.wraps(func)
113 def decorate_context(*args, **kwargs):
114     with ctx_factory():
--> 115         return func(*args, **kwargs)
File ~/litgpt/litgpt/api.py:294, in LLM.generate(self, prompt, …
```
> Fix error raising where max_returned_tokens > max_seq_length_setting

- pyproject.toml
Bumps to a new version so we can make a new release that includes the newly released Gemma 2 2B model which is now supported in LitGPT
> Version bumb for Gemma 2 2B release

- litgpt/config.py
- litgpt/data/base.py
- litgpt/data/deita.py
- litgpt/data/dolly.py
- litgpt/data/flan.py
- litgpt/data/json_data.py
- litgpt/data/lima.py
- litgpt/data/lit_data.py
- litgpt/data/longform.py
- litgpt/data/openwebtext.py
- litgpt/data/prepare_slimpajama.py
- litgpt/data/prepare_starcoder.py
- litgpt/data/text_files.py
- litgpt/data/tinyllama.py
- litgpt/data/tinystories.py
There were some issues with circular imports and also relative imports when importing form a Jupyter notebook that is in the same location as the cloned litgpt package. This is likely related to a clash between installed and local version of litgpt, but it's a common use case to have the litgpt package in the same folder as a script or Jupyter notebook (I remember Will bumping into this).
> Fix some issues with circular and relative imports

- litgpt/api.py
- tests/test_api.py
- tutorials/python-api.md
This adds `benchmark=True|False` arg to the `llm.generate()` method to optionally return some basic benchmark info:
```python
from pprint import pprint
llm = LLM.load(
model="microsoft/phi-2",
)
text, bench_d = llm.generate("What do llamas eat?", benchmark=True, top_k=1, max_new_tokens=500)
print(text)
pprint(bench_d)
```
```
Llamas are herbivores and primarily eat grass, leaves, and shrubs. They have a unique digestive system that allows them to efficiently extract nutrients from tough plant material.
{'GPU memory used in GB': 7.545283072,
'Inference speed in tokens/sec': 40.97021835066597,
'Seconds total': 0.659015282000837,
'Tokens generated': 27}
```
And
```python
del llm
llm = LLM.load(
model="microsoft/phi-2",
distribute=None
)
llm.distribute(devices=4, …
```
> Optionally return benchmark info in Python API

- README.md
I was just trying to show someone the models we support and was surprised that Phi-3 was not in the list. I removed the old Llama 2 model and added it.
> Swap old Llama model with Phi-3

- litgpt/api.py
- litgpt/deploy/serve.py
- tests/test_serve.py
I just noticed that the refactoring broke `litgpt serve` (the test for `serve` are a bit sparse because of how clunky and expensive the testing is here, so this wasn't caught before).
> Support the refactored API in litgpt serve

- README.md
- litgpt/config.py
- tutorials/download_model_weights.md
Adds the 123B Mistral Large model. 
Closes #1627
> Add Mistral Large 123B

- tutorials/python-api.md
Adds a `distribute=None` when using the sequential API so that it would also work with models too large to fit into memory of a single GPU.
> Add distribute=None to python-api.md

- README.md
- litgpt/api.py
- litgpt/utils.py
- tests/test_api.py
- tests/test_trainer_support.py
- tutorials/examples/ptl-trainer/litgpt_ptl_small.py
- tutorials/python-api.md
Makes the LitGPT LLM API compatible with the PyTorch Lightning Trainer while remaining minimal and user friendly. This PR implements all the necessary code to support models that fit on a single GPU. 
Support for models too large to fit on a single device will be handled in a separate PR.
> Make LitGPT LLM API compatible with PyTorch Lightning Trainer 1/2

- litgpt/api.py
- tests/test_api.py
- tutorials/python-api.md
Improved the benchmark utils because reporting the tok/sec for new PRs will be an important info moving forward.
Use the `.benchmark()` method to compare the computational performance of different settings. The `.benchmark()` method takes the same arguments as the `.generate()` method. For example, we can estimate the speed and GPU memory consumption as follows (the resulting numbers were obtained on an A10G GPU):
```python
from pprint import pprint
llm = LLM.load(
model="microsoft/phi-2",
distribute=None
)
llm.distribute(fixed_kv_cache_size=500)
text, bench_d = llm.benchmark(prompt="What do llamas eat?", top_k=1, stream=True)
print(text)
pprint(bench_d)
```
To get more reliably estimates, it's recommended to repeat the benchmark for multiple iterations via …
> Improved benchmark utils

- litgpt/api.py
Updated the `llm.benchmark()` method to make the number of generated tokens used for the calculation consistent with those in the CLI via `litgpt generate` and `litgpt chat`.
> Make number of generated tokens consistent with CLI

- litgpt/api.py
Addresses an issue where the benchmark utility would fail if the code is run outside a Git folder. This would happen, for example, if you run a script or notebook in VSCode in Studios, since Studios execute VSCode scripts or notebooks always in the home directory rather than in a subdirectory.
CC @apaz-cli
> Avoid error when executing benchmark util outside a git folder

- pyproject.toml
Bumb the version to 0.4.11 so we can make a new release with the recent fixes and new combined `generate` functionality.
> Bumb version to 0.4.11

- litgpt/prompts.py
This fixes the Falcon 7B Instruct prompt template, using the prompt specified in the [paper (pg 55)](https://arxiv.org/pdf/2311.16867). Why fixing it? @apaz-cli uses it as one of the models to run experiments for the batching since it's one of the models that has a sequence of stop tokens.
Below is a before-after the fix. You can see that this definitely helps.
Input:
```
Do not prefix your replies with 'Bot: '
User: What food do llamas eat?
```
Output:
```
Mini I'm not sure. Would you like me to look it up?
User Yes, please do.
Mini It seems like llamas are herbivorous and primarily eat grasses, plants, and other vegetation. They are not known for
```
Input:
```
Do not prefix your replies with 'Bot: '
User: What is 1+2?
```
Output:
```
Mini The answer is 3.
User 
```
Input:
```
What food …
```
> Fix falcon prompt template

- litgpt/data/base.py
- test.py
- tests/data/test_base.py
Resolves the EOT issue in #1682
> Preserve eos in encoding when max_seq_length = -1

- litgpt/model.py
- tests/test_batch.py
This allows to feed both `x`, `input_pos` of shape `(batch, T)` to the model.
I included a test that compares to running the batch items separately.
To add some commentary around the for loop:
- it's not terribly cool to use the for loop, but to reduce to `index_copy_`, we would need to fold the batch and indexed dimensions, which we cannot for KV-Cache,
- if we can use cudagraphs, it might not be too bad.
> add support for batched input_pos to model

- litgpt/generate/base.py
- pyproject.toml
- tests/test_batch.py
Still a bit rough around the edges. Debug prints are commented out. But it does the thing, so putting it up for review and feedback. Writing tests and cleaning it up.
* Does handle:
* Stop sequences (supports all litgpt models)
* Does not yet handle:
* Batched `input_pos`
* Padding to the left
* `include_eos`
Once `include_eos` works, I'd like to rewrite `generate_fn()` in terms of `batched_generate_fn()`.
Also we're going to have to re-benchmark everything of course.
> Add `batched_generate_fn()`

- litgpt/api.py
- litgpt/chat/base.py
- litgpt/finetune/adapter.py
- litgpt/finetune/adapter_v2.py
- litgpt/finetune/full.py
- litgpt/finetune/lora.py
- litgpt/generate/adapter.py
- litgpt/generate/adapter_v2.py
- litgpt/generate/base.py
- litgpt/generate/full.py
- litgpt/pretrain.py
LitGPT currently doesn't support MPS devices due to the `index_copy_` operation. I tried to come up with an alternative code but after a few hours, I couldn't figure out how to cover all the edge cases (the problem are some weird shapes in the new KV cache). 
So, I am currently disabling the support for MPS until we have support for that. Until then, MacBooks will run LitGPT code on CPU.
Fixes #1714
> Temporarily remove MPS device support

- pyproject.toml
Seems like litdata is softly requiring uvloop as a dependency:
```
Number of trainable parameters: 294,912
Number of non-trainable parameters: 162,322,944
The longest sequence length in the train data is 1035, the model's maximum sequence length is 1035 and context length is 2048
Verifying settings ...
uvloop is not installed. Falling back to the default asyncio event loop.
uvloop is not installed. Falling back to the default asyncio event loop.
uvloop is not installed. Falling back to the default asyncio event loop.
uvloop is not installed. Falling back to the default asyncio event loop.
```
> Add uvloop as a dependency

- litgpt/api.py
- litgpt/utils.py
Updates the default precision to return "bf16-true" instead of "16-true" on macOS devices that support MPS if CPU is used (since 16-true leads to unstable behaviors and nans and infs in the forward pass).
Fixes #1715
> Change default precision on macOS

- pyproject.toml
Bumbs the version so we can make a new release that works on macOS devices.
> Bumb for v0.4.12

- pyproject.toml
Increases the version after the latest stable release so it will be easier to debug user issues, since it will allow us to distinguish between the latest stable release and the current main branch in user version reports.
> Make 0.4.13.dev1 version

- litgpt/api.py
- litgpt/chat/base.py
- litgpt/finetune/adapter.py
- litgpt/finetune/adapter_v2.py
- litgpt/finetune/full.py
- litgpt/finetune/lora.py
- litgpt/generate/adapter.py
- litgpt/generate/adapter_v2.py
- litgpt/generate/base.py
- litgpt/generate/full.py
- litgpt/lora.py
- litgpt/model.py
- litgpt/pretrain.py
- tests/test_lora.py
- tests/test_model.py
Re-enables MPS support for LitGPT with an alternative `index_copy_` implementation.
> Enable MPS support for LitGPT

- tutorials/deploy.md
Adds a Studio showing how to connect LitGPT to a UI.
> Add Chainlit Studio

- tutorials/pretrain.md
Add the necessary explanation for using the continued pretraining correctly with the conversion script.
Fixes #1729
> Add pretrain conversion

- litgpt/model.py
Adds a more informative error message so users can debug the issue where the input text is too long.
Fixes #1717
> Add a more informative message in case text exceeds context size

- litgpt/config.py
- tests/test_model.py
The original Mistral v0.1 and Phi 3 models have sliding window attention. Adding it here for consistency with the original models.
Fixes #1598
> Add sliding window attention to Mistral and Phi 3

- tests/test_model.py
Removes accidental reassignment of the block size in sliding window tests (thanks for the note @Andrei-Aksionov !)
> Extend context length for sliding window tests

- tests/test_rope.py
Updates the RoPE test after transformers 4.45 introduced a backwards incompatible change. (CC @mtasic85)
> Update RoPE tests

- litgpt/tokenizer.py
- litgpt/utils.py
- tests/test_utils.py
Some files like the Llama 3.2 `generation_config.json` are not compatible with Python's json parser. This fixes it. Right now, it's not necessary to do it with other config files, but we can extend it later when necessary.
> Make json parsing more robust

- litgpt/utils.py
- tests/test_pretrain.py
This fixes #1743 
1. This changes bring support for optimizers which do not have "fused" parameter. Examples:
```yaml
optimizer: grokadamw.GrokAdamW
optimizer: bitsandbytes.optim.AdamW8bit
optimizer: bitsandbytes.optim.PagedAdamW8bit
```
2. Additionally, pytorch optimizers can be written in following format:
```yaml
optimizer: torch.optim.AdamW
optimizer: AdamW
```
3. In case of yaml config file, if value for `optimizer:` isn't `str` nor `dict`, error is thrown.
> Support for optimizers which don't have "fused" parameter such as grokadamw and 8bit bnb

- tests/test_adapter_v2.py
Mac does sometimes have slight numerical discrepancies, e.g., see https://github.com/Lightning-AI/litgpt/actions/runs/11058756360/job/30725503536?pr=1750
> Increase rtol and atol in Gemma 2 for macOS

- pyproject.toml
We can't have direct dependencies for new package releases to PyPI (see https://github.com/Lightning-AI/litgpt/actions/runs/10818557393/job/30014436744), so I am temporarily taking it out here.
> Temporarily take out thunder dependency for deployment

- litgpt/finetune/adapter.py
- litgpt/finetune/adapter_v2.py
- litgpt/finetune/lora.py
- tests/test_adapter.py
- tests/test_adapter_v2.py
- tests/test_lora.py
The bnb.nn.StableEmbedding is used during finetuning to replace the standard Embedding layer. As discussed #1769
Fixes #1769
> Add bnb.nn.StableEmbedding for quantized training

- litgpt/model.py
Suggests which parameters are missing if some of the new extra RoPE parameters are used (as suggested by @Andrei-Aksionov )
> Be more specific about missign RoPE parameters

- litgpt/config.py
Before, Llama 3.1 and 3.2 used a shorter max supported context length that would actually be supported by the new rope settings.
> Use correct Llama 3.1 and 3.2 context lengths

- litgpt/model.py
- litgpt/utils.py
- tests/test_utils.py
PR adds AMD support via the following:
- split nvlink check logic to branch on device name, as reported by torch - it looks for amd in the device name and uses `rocm-smi --showtopotype` instead of the nvidia-smi one, for AMD.
- rewrite the `build_rope_cache` to use a vectorized approach instead of indexing into the nonzero mask - ~I did not bench performance vs. main, but~ should be quicker as well as a bonus. The previous code did not work on my hardware, probably due to device detection issues, and resulted in `build_rope_cache` receiving `device=None` which then tries the nonzero indexing on the `meta` device and fails because of missing custom kernels :man_shrugging: 
- ~added debug prints in `build_rope_cache`, since there was no logger (will remove once reviewed, if you have …
> AMD (MI250X) support

- .github/azure-gpu-test.yml
- pyproject.toml
Temporarily pin PyTorch to <= 2.4.1 until the Lightning package is updated to support 2.5.0 (used for Bitsandbytes plugin and some others).
> Pin to PyTorch 2.4.1

- litgpt/finetune/adapter.py
- litgpt/finetune/adapter_v2.py
- litgpt/finetune/full.py
- litgpt/finetune/lora.py
Fixes an issue where the finetuning scripts always perform an additional step that goes into the next epoch.
Fixes #1793
> Fix step iteration bug in finetuning scripts

- pyproject.toml
Bump version so we can make a 0.5.2 release with bug fixes and pinned PyTorch version (until we have PyTorch 2.5 compatibility)
> 0.5.2 release

- litgpt/config.py
- tests/test_model.py
- tutorials/download_model_weights.md
Fixes #1739 
I think it's going to work
> Add Phi 3 128k model

- litgpt/generate/tp.py
It makes `litgpt` importable in the PyTorch build compiled without the distributed component. Fixes https://github.com/Lightning-AI/litgpt/issues/1792.
> Move distributed all_reduce import into a function

- litgpt/api.py
Fixes a bug where the precision was accidentally hardcoded to float 32
Fixes #1814
> Remove hardcoded 32-precision conversion

- litgpt/data/prepare_slimpajama.py
- pyproject.toml
Rework of https://github.com/Lightning-AI/litgpt/pull/1838
> Restore SlimPajama preprocessing code

- README.md
- litgpt/config.py
- litgpt/prompts.py
- litgpt/scripts/convert_hf_checkpoint.py
- litgpt/scripts/convert_lit_checkpoint.py
- tests/test_convert_lit_checkpoint.py
- tests/test_model.py
- tests/test_tokenizer.py
- tutorials/download_model_weights.md
https://qwenlm.github.io/blog/qwq-32b-preview/
Reason for adding:
- Latest Qwen reasoning model that beats O1
- Currently it's a 32B preview version, but there will definitely be more QwQ releases in the near future.
Note: QwQ is based off Qwen2.5 architecture.
> Add QwQ-32B-Preview

- README.md
- litgpt/config.py
- tests/test_convert_lit_checkpoint.py
- tests/test_model.py
- tutorials/download_model_weights.md
https://mistral.ai/news/mixtral-8x22b/
More powerful and SOTA MoE model than the existing Mixtral-8x7b series.
Also addresses #1448.
> Add Mixtral-8x22B

- README.md
- litgpt/config.py
- tests/test_model.py
- tutorials/download_model_weights.md
Meta's newest LLM with groundbreaking performance that beats Llama-3.1-405B.
https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct
Adding so that the community can start playing with the model ASAP.
> add Llama-3.3-70B-Instruct

- README.md
- litgpt/config.py
- litgpt/prompts.py
- litgpt/tokenizer.py
- tests/test_model.py
- tutorials/download_model_weights.md
Addresses issue #1768 
(From original issue)
Salamandra is a model based on LLaMA that has been trained from scratch using 35 European languages, including minority languages like Catalan and Basque, making it unique compared to other models primarily focused on English.
Salamandra comes in four versions:
[Salamandra 7B](https://huggingface.co/BSC-LT/salamandra-7b)
[Salamandra 7B Instruct](https://huggingface.co/BSC-LT/salamandra-7b-instruct)
[Salamandra 2B](https://huggingface.co/BSC-LT/salamandra-2b)
[Salamandra 2B Instruct](https://huggingface.co/BSC-LT/salamandra-2b-instruct)
The Instruct versions have been fine-tuned for instruction-based tasks, while the non-instruct versions remain general-purpose.
Adding Salamandra to lit-gpt would enrich the framework by introducing multilingual …
> add Salamandra

- litgpt/config.py
Block size for Qwen2.5 Coder series is wrongly specified.
Correct block size is 32768 across all model sizes.
> Qwen2.5: fix block size for Coder series

- README.md
Current llama3.3 url in README.md is wrong and leads to a 404 page.
> fix llama3.3 readme url

- litgpt/api.py
Fixes an [error](https://dev.azure.com/Lightning-AI/lit%20Models/_build/results?buildId=221553&view=logs&j=8f314803-5dd0-5dfc-f80d-9e97f23b827e&t=bc8d09c9-6e7d-5a58-973b-84e67a1cfd78) in Thunder workflow.
Thunder CI workflow uses the latest dev version of PyTorch, where `weights_only=True` will be by default. 
(Now it's `weights_only=False`.)
> FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`
Since LitGPT loads …
> Set torch.load(..., `weights_only=False`) in litgpt/api.py

- litgpt/config.py
- tutorials/download_model_weights.md
More recent version of Mistral-Large model: [mistralai/Mistral-Large-Instruct-2411](https://huggingface.co/mistralai/Mistral-Large-Instruct-2411)
> Add Mistral-Large-Instruct-2411

- pyproject.toml
One thing that I didn't notice while looking how Sebastian [usually makes releases](https://github.com/Lightning-AI/litgpt/pull/1815/files), is that we have to temporarily remove Thunder from the list of dependencies.
The last release of Thunder was done in March, but we need the latest version, so the code installs the version from main branch.
That causes an error during building a package: [link](https://github.com/Lightning-AI/litgpt/actions/runs/12466677354/job/34794646118#step:5:192).
This error occurs because PyPI does not allow uploading distributions with direct dependencies specified via URLs (e.g., git+https://...) in `pyproject.toml` or `setup.py`.
> Temporary remove Thunder to make a release

- pyproject.toml
1. Increases version for the new development cycle
2. Restores back Thunder in the list of dependencies after it was removed in #1884
> Post-release setup for 0.5.5.dev1

- litgpt/prompts.py
Multiple SOTA models, including the ones currently added to the framework, use the same ChatML template, only differing in terms of system prompts. This PR unifies them into a single "ChatML" PromptStyle class in order to adhere to the DRY principle.
> ChatML prompt template

- extensions/thunder/unsloth/executor.py
- litgpt/adapter.py
- litgpt/adapter_v2.py
- litgpt/config.py
- litgpt/generate/base.py
- litgpt/lora.py
- litgpt/model.py
- tests/test_generate.py
- tests/test_generate_adapter.py
Mostly refactoring and small fixes:
- `config.sliding_window_layer_period` instead of overwriting `config.sliding_window_layer_placing` (str to int)
- Comment on `config.attention_logit_softcapping`: Will hit performance if this is used
- `cos`, `sin` passed down in `GPT.forward` must have batch dimension if `input_pos` is `None`. This probably worked because PyTorch is adding singleton dimensions at the front of a shape for broadcasting, but it did confuse me.
- `Block.forward`: Missed `self.post_mlp_norm` if `parallel_residual`. BTW: None of your models have `parallel_residual = True`, is anybody using this?
Not doing anything new. Feel free to reject, but this would help to make the code easier to understand.
> Small fixes and refactoring

- pyproject.toml
In #1796 the PyTorch version was restricted to 2.4.1 and in #1765 to PyTorch-Lightning 2.4.
Now the latest version of PTL is 2.5 and it now supports torch 2.5.
This PR bumps both versions.
Additionally, a newer version of PTL required a newer version of Bitsandbytes.
> Bump PyTorch, PyTorch-Lightning and BnB versions

- .github/workflows/check-links.yml
A new version of mistune, that is used in check links workflow, has just been updated.
Sadly, it's incompatible with the version of nbconvert used in `pytest-check-links`, which results in this [error](https://github.com/Lightning-AI/litgpt/actions/runs/12549175840/job/34989788262?pr=1894).
This PR restricts from installing the latest version of mistune in the workflow.
> Pin version of mistune in check links workflow

- litgpt/adapter.py
- litgpt/adapter_v2.py
- litgpt/generate/base.py
- litgpt/lora.py
- litgpt/model.py
- litgpt/utils.py
- tests/test_model.py
- tests/test_rope.py
- tests/test_unsloth_executor.py
- Ensure that KVCache buffers are only as large as config.n_query_groups
- Shrink buffers returned by KVCache to just cover input_pos entries
- Clean up children of classes in `model.py`, in particular remove `forward` copies
> Some improvements for KV caching

- litgpt/scripts/download.py
Addresses the speed issue discussed in #1886. I think the issue is that the setting needs to happen before importing huggingface packages @Andrei-Aksionov .
> Improve HF download speed

- litgpt/utils.py
- tests/test_utils.py
- we need to deal with UntypedStorage (easy)
- PyTorch's safe unpickling only implements pickle protocol 2, so we change the incremental save to that.
-
> fix incremental save for PyTorch 2.6

- litgpt/data/alpaca_2k.py
- litgpt/model.py
- tests/test_rope.py
Gemma3 uses the following config for rope:
```
"rope_scaling": {
"factor": 8.0,
"rope_type": "linear"
},
```
I added a linear rope type within `extra_configs` so that it can properly calculate theta.
Currently the HF transformer version does not have Gemma3, so it is skipped for pytest. With the newest version, it passes the test: see [here](https://www.loom.com/share/c4f69e1f3c5244a18d19734f24e9f9bb?sid=3926848e-fe94-472a-9389-99bdcd96110a).
> feat: add linear rope type

- .github/workflows/cpu-tests.yml
- litgpt/data/alpaca_2k.py
- pyproject.toml
- tests/convert/test_lit_checkpoint.py
- tests/test_model.py
- tests/test_rope.py
When working on Gemma3, the updated version of `transformers` was needed. However, when updating, error occurred and this PR fixes them.
This is somewhat a follow up to [this](https://github.com/Lightning-AI/litgpt/pull/1969).
> feat: update tests for transformers 4.50.2

- litgpt/config.py
- litgpt/model.py
For Gemma 3, local and global rotary embeddings take different base frequencies. Therefore, `rope_indices` provide a way to select appropriate embeddings by selecting the proper dimension for `cos` and `sin` values.
> feat: add rope indices

- .github/workflows/cpu-tests.yml
- litgpt/config.py
- litgpt/model.py
- tests/test_model.py
Different models have different sliding window pattersn that are difficult to configure with simple `stride` and `offset` parameters. For instance, in the case of Gemma 3, it applies sliding for 5 layers and skips the next layer (which is difficult to represent with stride and offsets). Other supported models that uses sliding windows so far used either sliding windows for all layers or alternating layers; however, for future variations of sliding windows, I think this approach is the most straight forward approach.
> fix: replace sliding window configuration parameters to sliding windows indices

- litgpt/model.py
Hi there 👋 
One more small perf improvement.
While looking at the stack track from PyTorch profiling, I've noticed that `KVCache.forward` call takes a surprisingly long amount of time (relatively, of course).
If to zoom-in, one can see that there are a couple of `__setattr__` calls.
That is caused by these two lines:
https://github.com/Lightning-AI/litgpt/blob/3d66f32b894b16415bc85839b9c6ba15f72af07e/litgpt/model.py#L793-L795
If `self.k` and `k` (and similarly `self.v` and `v`) are already of the same dtype, the `.to(k.dtype)` operation is effectively a no-op. However, PyTorch still incurs some overhead in checking and potentially preparing for the operation.
--------------
A quick benchmark with `Qwen2.5-7B-Instruct` on `Nvidia L4`, 3 runs of generating 500 new tokens, gave me such …
> Cast tensors in KVCache only when needed

- litgpt/generate/base.py
- litgpt/generate/sequentially.py
- litgpt/generate/speculative_decoding.py
- litgpt/model.py
- tests/test_model.py
Hi there 👋 
While I was profiling the code to see whether I can improve the speed of speculative decoding, I noticed two weird things:
1. Relatively long KV-cache call (that's whole another story)
2. `cudaStreamSynchronize` call in `CausalSelfAttention.forward` from `model.py` 
> [!NOTE]
> All number are provided for `Qwen2.5-7B-Instruct` on `Nvidia L4`
This is caused by implicit call of `.item()` when doing slicing with a tensor.
https://github.com/Lightning-AI/litgpt/blob/3d66f32b894b16415bc85839b9c6ba15f72af07e/litgpt/model.py#L418-L421
It's worth admitting, when @mseeger added `input_pos_maxp1` he initially used it as a Python integer, but I insisted on changing it to a tensor, so it works properly with the rest of the code (for example a function that moves arguments to a device in …
> input_pos_maxp1 as a Python integer

- .github/workflows/cpu-tests.yml
- .pre-commit-config.yaml
- README.md
Adding testing for latest python versions since we have these tags in package metadata as we are compatible...
Since the PR event has changed this PR is running with dispatch on this branch: https://github.com/Lightning-AI/litgpt/actions/runs/14858720043
Fixing alignement in readme
> add testing for py3.12 & py3.13

- .github/workflows/cpu-tests.yml
This reduces false signals from PRs by omitting the failing test due to not avalible HF token
> ci: run `pull_request` only on own PRs

- litgpt/config.py
- litgpt/utils.py
- tests/test_config.py
- tests/test_utils.py
I have some code which constructs and writes out to YAML files configs which are used to queue up litgpt training jobs on remote machines. Unfortunately this code starts up really slowly because importing the `litgpt.config` submodule pulls in a *ton* of transitive dependencies due to its `from litgpt.utils import find_multiple` line (eventually torch, triton, etc. are imported). This causes as much as a 30+ second delay to any script I write that manipulates litgpt config objects.
I noticed that `find_multiple` is actually only ever used in `litgpt.config` anyhow, so I was wondering if it would be okay to scoot this function over and remove the dependency from `config` on `utils`. With this change, it is possible to write code which imports the config submodule alone and thus runs very …
> Remove dependency from config to utils

- litgpt/deploy/serve.py
- tests/test_serve.py
Demo: https://www.loom.com/share/e3243c822aca496fb5f86e4697bd439a
Currently, the library errors on serving models with the OpenAI spec if a chat template is not included with the tokenizer config.  Some of the models we support, like microsoft Phi do not contain one.  This PR adds a basic fallback template that can be used in the case one does not exist.
This PR fixes serving microsoft phi and probably some others
> fix: Add fallback chat template

- litgpt/data/text_files.py
- pyproject.toml
- tests/data/test_textfiles.py
- tests/data/test_tinystories.py
Demo: https://www.loom.com/share/6644999da8484f7483df27defb21765a
Recent versions of litdata have breaking changes that affect pretraining of text files in litgpt.  The issue is that `PyTreeLoader` is the default loader and `TokensLoader` needs to be explicitly specified.  This includes 0.2.45, which is the current default installed in Lightning studios.  As a result, pretraining is broken when installing litgpt in a default studio.
> fix: Pretraining text files with recent litdata versions

- tests/test_evaluate.py
see the runs on several PRs and master, and seems this is quite flaky and may be debugged in the future
> tests: mark `test_evaluate_script` as flaky

- .azure/gpu-test.yml
- tests/conftest.py
This PR marks the `test_hf_for_nemo` test as `xfail` for the `Qwen` model due to a known issue in `TorchDynamo` involving SymInt.
The issue originates in Thunder's backend and is currently blocked on a fix from NVIDIA.
> Xfail Thunder integration test due to Dynamo bug

- pyproject.toml
resolves thunder extra tests
```
def populate_item_wrappers(l):
ctx: InterpreterCompileCtx = get_interpretercompilectx()
if not ctx._with_provenance_tracking:
return
assert isinstance(l, WrappedValue)
if wrapped_isinstance(l, (list, tuple)):
if l.item_wrappers is None:
l.item_wrappers = [None for _ in range(len(l.value))]
assert isinstance(l.item_wrappers, list)
assert len(l.value) == len(l.item_wrappers), f"{len(l.value)=} {len(l.item_wrappers)=}"
for i, v in enumerate(l.value):
if l.item_wrappers[i] is None:
wv = wrap_binary_subscr(v, l, i)
l.item_wrappers[i] = wv
return
if wrapped_isinstance(l, dict):
assert isinstance(l.item_wrappers, dict)
>           for k, v in l.value.items():
E           RuntimeError: dictionary changed size during iteration …
```
> req: pin `bitsandbytes>=0.45.2,<0.45.5`

- pyproject.toml
Transformers version bump for more recent model support
> Transformers version bump

- litgpt/model.py
Issue raised in https://github.com/Lightning-AI/litgpt/issues/2074
> doc: add `n_query_groups` to attention notation table

- pyproject.toml
```
>                   raise RuntimeError(f"Dataset scripts are no longer supported, but found {filename}")
E                   RuntimeError: Dataset scripts are no longer supported, but found logiqa.py
> pin: restrict datasets version to <4.0.0 for compatibility

- .azure/gpu-test.yml
- .lightning/workflows/tests.yaml
addresses `E       RuntimeError: Deterministic behavior was enabled with either torch.use_deterministic_algorithms(True)orat::Context::setDeterministicAlgorithms(true), but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility`
> gpu: use `CUBLAS_WORKSPACE_CONFIG: ":4096:8"`
