generate.py, howto/customize_paths.md, howto/download_weights.md, lit_stablelm/model.py, scripts/convert_hf_checkpoint.py, scripts/download.py
```bash
python scripts/download.py --repo_id EleutherAI/pythia-70m --local_dir checkpoints/hf-pythia/pythia-70m
```
```bash
python scripts/convert_hf_checkpoint.py --output_dir checkpoints/lit-pythia/pythia-70m --ckpt_dir checkpoints/hf-pythia/pythia-70m
```
```bash
python generate.py --prompt "Hello, my name is" --checkpoint_path checkpoints/lit-pythia/pythia-70m/lit-stablelm.pth --config_path checkpoints/lit-pythia/pythia-70m/config.json --tokenizer_path checkpoints/lit-pythia/tokenizer.json --tokenizer_config_path checkpoints/lit-pythia/tokenizer_config.json
```
=> Support Pythia checkpoints

tests/test_generate.py
=> Load smaller model in generation test

lit_stablelm/model.py
Fixes #8 
Testing script:
```bash
#!/bin/bash
set -ex
ckpts=( \
"stabilityai/stablelm-base-alpha-3b" \
"stabilityai/stablelm-base-alpha-7b" \
"stabilityai/stablelm-tuned-alpha-3b" \
"stabilityai/stablelm-tuned-alpha-7b" \
"EleutherAI/pythia-70m" \
"EleutherAI/pythia-160m" \
"EleutherAI/pythia-410m" \
"EleutherAI/pythia-1b" \
"EleutherAI/pythia-1.4b" \
"EleutherAI/pythia-2.8b" \
"EleutherAI/pythia-6.9b" \
"EleutherAI/pythia-12b" \
)
for item in "${ckpts[@]}"
do
python scripts/download.py --repo_id "$item" --local_dir "checkpoints/hf-$item"
python scripts/convert_hf_checkpoint.py --ckpt_dir "checkpoints/hf-$item" --output_dir "checkpoints/lit-$item" 
done
```
=> Add all StableLM and Pythia configs

README.md, generate.py, howto/inference.md, lit_stablelm/quantization.py, lit_stablelm/utils.py
Fixes #14 
Need to update the quantization section. Currently non functional: #18
=> Update memory usage in docs

README.md, chat.py
Fixes #6
```shell
$ python chat.py 
Loading model 'checkpoints/lit-stablelm/stablelm-tuned-alpha-3b/lit-stablelm.pth' with {'block_size': 4096, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 50688, 'n_layer': 16, 'n_head': 32, 'n_embd': 4096, 'rotary_percentage': 0.25}
>> Prompt: Why is Lightning a great place to work at?
>> Reply: There are several factors that make lightning a great place to work at. One major factor is the magnetic field that develops in the Earth's magnetosphere. The Earth's magnetic field is generated by a large number of giant glowing quasars in our galaxy, which are so far away that they interact with each other and with electrons in the solar wind. This collisionless streaming motion of electrons generates a powerful electric current in the …
```
=> Add interactive chatting script

howto/pythia.md
Fixes #7 
Preview: https://github.com/Lightning-AI/lit-stablelm/blob/carmocca/pythia-howto/howto/pythia.md
=> Add Pythia howto

chat.py, generate.py, lit_stablelm/model.py, lit_stablelm/tokenizer.py, scripts/convert_hf_checkpoint.py, tests/test_chat.py, tests/test_generate.py, tests/test_model.py, tests/test_rope.py, tests/test_tokenizer.py
https://www.together.xyz/blog/redpajama-models-v1
For the howto, do we want to add an `INCITE.md` page or merge it with `pythia.md` (#19) into a `checkpoints.md` file?
=> Support INCITE checkpoints

howto/RedPajama-INCITE.md, howto/inference.md, howto/pythia.md
Addressing https://github.com/Lightning-AI/lit-stablelm/pull/24#pullrequestreview-1415718606
=> Add INCITE howto

chat.py, generate.py, lit_stablelm/__init__.py, lit_stablelm/config.py, lit_stablelm/model.py, tests/test_generate.py, tests/test_model.py
Removes clutter from `model.py`
=> Split configs into a separate file

howto/download_weights.md
Adds a missing package installation for downloading the weights from HF hub.
=> Update download instructions

README.md, finetune_adapter.py, generate_adapter.py, howto/finetune_adapter.md, lit_stablelm/adapter.py, lit_stablelm/tokenizer.py, scripts/convert_hf_checkpoint.py, scripts/prepare_alpaca.py, tests/test_adapter.py, tests/test_tokenizer.py
Fine tuning adapter on consumer grade graphic card ~12GB VRam 
Part of #20 
The files were copied and adapted from the Lit-LLaMA repo: https://github.com/Lightning-AI/lit-llama
=> Porting adapter from lit-llama

README.md, howto/finetune_adapter.md
=> Update howto for finetuning with adapter

finetune_adapter.py, lit_parrot/adapter.py, lit_parrot/config.py, lit_parrot/model.py
Fixes the issue when another model available from the `config.py` is used.
=> Fix model configuration

howto/download_pythia.md, howto/download_redpajama_incite.md, howto/download_stablelm.md
this PR adds repo_id arg to fix the error:
`download.py: error: Unrecognized arguments: togethercomputer/RedPajama-INCITE-Base-3B-v1`
=> fix unrecognized command error

lit_parrot/config.py
Fixes https://github.com/Lightning-AI/lit-parrot/issues/50
=> Fix n_embd for larger Pythia models

chat.py, generate.py, generate_adapter.py
Added code specific for `xla` devices which is used when Fabric's device type is `xla`
=> Add generation and chat scripts support for XLA devices

lit_parrot/model.py
=> fix unpacking error

lit_parrot/adapter.py
Sorry, the previous PR was sloppy. The fix should be on adapter.py
#73
=> fix unpack issue

scripts/download.py
Part of https://github.com/Lightning-AI/lit-llama/issues/295
=> Do not use symlinks when downloading for cloud support

chat.py, generate.py, generate_adapter.py, lit_parrot/adapter.py, lit_parrot/model.py
fixes #77 
Add reset method to model and call it before returning in generate function.
=> reset cache after generation

howto/tpus.md
Adjusting times in `howto/tpus.md` due to changes in https://github.com/Lightning-AI/lit-parrot/pull/91.
=> tpu howto timing adjustments

lit_parrot/config.py, scripts/convert_hf_checkpoint.py, tests/test_utils.py
This reverts commit 554b7b3.
Addresses https://github.com/Lightning-AI/lit-parrot/pull/68/files#r1196427429
=> Revert "Adding `vocab_size` to `config.py` (#68)"

howto/download_pythia.md, howto/download_redpajama_incite.md, howto/download_stablelm.md
Add `pip install huggingface_hub` for downloading weights using huggingface_hub to howtos.
Fixes #96
=> doc: add `pip install huggingface_hub` to howtos

chat.py, finetune_adapter.py, generate.py, generate_adapter.py, lit_parrot/model.py, tests/test_chat.py, tests/test_generate.py
Fixes #65
Re-do of https://github.com/Lightning-AI/lit-parrot/pull/71
Closes #93
cc @ArturK-85
=> `max_returned_tokens` as a generate input

README.md, chat.py, howto/download_falcon.md, lit_parrot/config.py, lit_parrot/model.py, lit_parrot/quantization.py, lit_parrot/tokenizer.py, scripts/convert_hf_checkpoint.py, scripts/download.py, tests/test_model.py
See title.
40B in progress at #102
=> Support Falcon 7B

finetune_adapter.py, howto/finetune_adapter.md
Addressing https://github.com/Lightning-AI/lit-parrot/pull/94#issuecomment-1567364223
=> Update howto for finetuning on MPS

finetune_adapter.py, finetune_adapter_v2.py, generate_adapter.py, generate_adapter_v2.py, howto/finetune_adapter.md, lit_parrot/adapter.py, lit_parrot/adapter_v2.py
Closes https://github.com/Lightning-AI/lit-parrot/pull/101
Fixes issues stemming from Falcon support
=> Adapter fixes

chat/base.py, finetune/adapter.py, finetune/adapter_v2.py, generate/adapter.py, generate/adapter_v2.py, generate/base.py, howto/inference.md, lit_parrot/utils.py, quantize/gptq.py, tests/test_adapter.py, tests/test_adapter_v2.py, tests/test_model.py
Closes https://github.com/Lightning-AI/lit-parrot/issues/13
Same as https://github.com/Lightning-AI/lit-llama/pull/360
Some minor bf16 fixes included
=> Use `init_module(empty_init)`

pretrain/redpajama.py
This PR adds changes specific for pretraining on TPUs. Most of these changes are based from #110
=> [TPU] XLA changes for pretraining

finetune/adapter.py, finetune/adapter_v2.py, finetune/lora.py, scripts/prepare_alpaca.py
Fixes https://github.com/Lightning-AI/lit-parrot/pull/127#issuecomment-1587732494
=> Automatically load the most efficient max_seq_length

finetune/adapter.py, finetune/adapter_v2.py, finetune/lora.py, lit_parrot/adapter.py, pretrain/openwebtext.py, pretrain/redpajama.py
Follow-up to https://github.com/Lightning-AI/lit-parrot/pull/147
=> Integrate the speed monitor in all training scripts

finetune/adapter.py, finetune/adapter_v2.py, finetune/lora.py, lit_parrot/speed_monitor.py, pretrain/openwebtext.py, pretrain/redpajama.py
=> Support non-CUDA devices with SpeedMonitor

lit_parrot/packed_dataset.py, scripts/prepare_alpaca.py
Small edit to scripts/prepare_alpaca.py to fix codec errors I ran into when finetuning for Falcon.
=> Fixed codec errors in prepare_alpaca script

lit_parrot/adapter.py, lit_parrot/model.py
As proposed in https://github.com/Lightning-AI/lit-llama/issues/382
=> Use index_copy_ to reduce memory copies

chat/base.py, finetune/adapter.py, finetune/adapter_v2.py, finetune/lora.py, generate/adapter.py, generate/adapter_v2.py, generate/base.py, generate/lora.py, howto/finetune_adapter.md, lit_parrot/adapter.py, lit_parrot/adapter_v2.py, lit_parrot/lora.py, lit_parrot/utils.py, pretrain/openwebtext.py, pretrain/redpajama.py, tests/test_adapter.py, tests/test_adapter_v2.py, tests/test_lora.py
Replaces DeepSpeed with FSDP
Requires https://github.com/Lightning-AI/lightning/pull/17845
Closes #116 
Closes #177 
Closes #169
Falcon 7b takes 32 GB max memory allocated using 2 devices and 32-true or bf16-mixed precision.
Loss is NaN, requires further debugging into why.
=> Use FSDP everywhere

lit_parrot/speed_monitor.py
PR to add FLOPS numbers for benchmarking when using TPUs.
Follow up to https://github.com/Lightning-AI/lit-gpt/pull/147#discussion_r1230009025
=> [TPU] added numbers for TPU FLOPS

finetune/adapter.py, finetune/adapter_v2.py, finetune/lora.py, pretrain/openwebtext.py, pretrain/redpajama.py
Fixes https://github.com/Lightning-AI/lit-gpt/issues/185
=> Fix FSDP initialization

lit_gpt/utils.py
=> Fix typo in utils.py

scripts/prepare_alpaca.py
the data is getting saved as test.pt instead of val.pt
=> val.pt -> test.pt

README.md, chat/base.py, lit_gpt/config.py, lit_gpt/model.py, tutorials/download_longchat.md
Adds https://lmsys.org/blog/2023-06-29-longchat
Using https://kaiokendev.github.io/context
=> Add LongChat support

pretrain/redpajama.py
- Added state to the pretraining script for redpajama
- Added `--resume path` option to pass in a checkpoint to resume from or `--resume True` for auto-resuming the checkpoint file with the highest iter number
In the future, we could consider making the script use AttributeDict or similar for convenience rather than indexing into a dict.
=> Stateful pretraining script for redpajama

pretrain/openwebtext.py
Same changes as for #229 applied to the OpenWebtext pretraining code.
=> Stateful pretraining script for openwebtext

finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, pretrain/openwebtext.py, pretrain/redpajama.py, tests/test_adapter.py, tests/test_adapter_v2.py, tests/test_full.py, tests/test_lora.py
These tests are end-to-end and assert:
- some of the logs are produced
- the speedmonitor produces a csv
- some checkpoints are saved
=> Add tests for the finetuning scripts

scripts/convert_hf_checkpoint.py
Fixes (for this repo) https://github.com/Lightning-AI/lit-llama/issues/414.
I don't see any use to the `dtype` argument right now, so I removed it
I ran Vicuna with and without this change and it generated the same output.
=> Do not change the dtype when converting checkpoints

tutorials/finetune_lora.md
=> Update missing link the lora finetuning tutorial

lit_gpt/config.py
**link :** https://huggingface.co/NousResearch/Nous-Hermes-13b
Since this model follows the llama architecture, I just added one dictionnary in the config.py file, in the open LLama part with the corresponding configuration.
**configuration file** : https://huggingface.co/NousResearch/Nous-Hermes-13b/blob/main/config.json
=> Add support for Nous Hermes 13b model

lit_gpt/lora.py, tests/test_lora.py
Fixes https://github.com/Lightning-AI/lit-gpt/issues/250
=> Fix quantization and LoRA inheritance issue

lit_gpt/lora.py, lit_gpt/utils.py
Fixes https://github.com/Lightning-AI/lit-gpt/issues/261
=> Fix LoRA Linear calls

finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, lit_gpt/speed_monitor.py, lit_gpt/utils.py, pretrain/openwebtext.py, pretrain/openwebtext_trainer.py, pretrain/redpajama.py
Port of `pretrain/openwebtext.py` using the `Trainer`.
=> Pretrain script with the Trainer

generate/lora.py
Fixes https://github.com/Lightning-AI/lit-gpt/issues/288
cc @Andrei-Aksionov
=> Fix LoRA generation

tutorials/quantize.md
Addresses cosmetic issues by @Andrei-Aksionov mentioned in #312
=> Quantize cosmetic fixes

tutorials/finetune_lora.md, tutorials/quantize.md, tutorials/tpus.md
Fixes #305 by updating note admonitions to new GFM convention.
=> Fix Note Admonition

scripts/convert_lit_checkpoint.py, tests/test_convert_lit_checkpoint.py, tutorials/convert_lit_models.md
=> Update convert_lit_checkpoint to allow --checkpoint_name as CLI arg

lit_gpt/lora.py
There is no need to have `self.merge` attribute. Previously it could be used to prevent from merging pretrained and LoRA weights when `self.train`/`self.eval` method is called. Since now we have a separate method for it (self.merge) we can get rid of the attribute.
This change was discussed in https://github.com/Lightning-AI/lit-gpt/pull/296#discussion_r1271297881
=> Drop `merge_weights` argument in LoRALayer

lit_gpt/lora.py
Hello there 👋 
This is the last piece of my large [PR](https://github.com/Lightning-AI/lit-gpt/pull/325) (that was fractured into smaller pieces like this one).
This one is pretty simple. It includes:
1. Removal of multiple spaces withing sentences
2. Utilization of ability of `LoRALinear` to behave as a `nn.Linear` if provided rank is less or equal to zero
3. Addition of shapes in `GPT.forward` method
=> LoRA small enhancements

lit_gpt/lora.py, scripts/convert_lit_checkpoint.py, tests/test_convert_lit_checkpoint.py
=> Unwrap in `convert_lit_checkpoint` if `model` key is present

scripts/convert_lit_checkpoint.py, tests/test_convert_lit_checkpoint.py
- removed extra dict causing TypeError
- added appropriate test
- also applied formatting to test file
fixes #347
=> Remove Additional Dict Causing TypeError for Llama Models

README.md
Add model table with references
=> add model table with references

README.md
This PR updates the URL and title of the contributing guide.
=> Update Contributing Post Path in README

finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, lit_gpt/utils.py, pretrain/openwebtext.py, pretrain/redpajama.py, tests/test_utils.py
Decided to simplify this code when things got crowded in #379 #351
=> Simplify printing of number of trainable weights

lit_gpt/model.py, lit_gpt/rmsnorm.py, pretrain/openwebtext.py, pretrain/redpajama.py
Sets `empty_weights=True` for training with FSDP and meta-device support.
Tested with pythia-70m, pythia-1b, falcon-7b
=> FSDP empty weight initialization for pretraining scripts

README.md
The header spacing was very inconsistent. Some sections had spacing between headers and others didn't, which made it look a bit messy. I applied the same spacing to all headings to improve readability and aesthetics.
=> Make header spacing consistent to improve readability

eval/lm_eval_harness.py, eval/lm_eval_harness_lora.py, finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, generate/adapter.py, generate/adapter_v2.py, generate/base.py, generate/full.py, generate/lora.py, lit_gpt/speed_monitor.py, pretrain/openwebtext.py, pretrain/openwebtext_trainer.py, pretrain/redpajama.py, quantize/gptq.py
Ref: https://www.webucator.com/article/python-clocks-explained
=> Prefer `perf_counter` over `time`

finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, pretrain/openwebtext.py, pretrain/openwebtext_trainer.py, pretrain/redpajama.py
Requested in https://github.com/Lightning-AI/lit-gpt/pull/275#issuecomment-1677632256
=> Print max memory allocated at the end of training

finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py
fixes https://github.com/Lightning-AI/lit-gpt/issues/407#issuecomment-1678507201
=> fix(finetune): shift logits / targets in val loss calc

lit_gpt/adapter.py, lit_gpt/adapter_v2.py, lit_gpt/lora.py, tests/test_adapter_v2.py, tests/test_lora.py
=> Fix LoRA checkpoint loading

scripts/prepare_dolly.py
Implementing the Dolly dataset, which is urgently needed for the NeurIPS competition (none of our current datasets is supported atm).
Seems to work fine and looks good to me, but I need to run an additional finetuning test (GPUs are currently busy due to QLoRA experiments)
Fixes #394
=> Dolly 15k instruction finetuning dataset

README.md, tutorials/neurips_challenge_quickstart.md
Adds a minimal tutorial to guide newcomers through the process of using Lit-GPT. We have a lot of tutorials, which are great,  but they are more detailed. Some people are looking for minimal document with the sequence of steps before reading these more in-depth tutorials.
=> NeurIPS challenge quickstart guide

tutorials/pretrain_openwebtext.md
As the title above suggests, this adds the documentation for OpenWebText pretraining.
=> Adds documentation for OpenWebText pretraining

README.md, pretrain/redpajama.py, tutorials/pretrain_redpajama.md
Adds documentation for pretraining on Red Pajama.
=> Set up RedPajama docs (and RedPajama pretraining on Llama 2 7B)

chat/base.py, lit_gpt/config.py, lit_gpt/tokenizer.py, lit_gpt/utils.py, scripts/convert_hf_checkpoint.py, scripts/download.py, scripts/prepare_dolly.py
This pull request adds a new configuration for the `stablecode-completion-alpha-3b` model from StabilityAI and Restructured code related to StabilityAI models configurations.
This PR addresses issue #427.
=> Add Configuration for StabilityAI's StableCode-Completion-Alpha-3B Model

README.md
I noticed that we don't have documentations for Nous-Hermes and Platypus. Worthwhile adding those?
=> Update Supported Model List

README.md
- added Stable Code
- fixed Vicuna link
- put LMSYS models next to each other
=> Update supported model table

README.md
Adds dataset tutorial to readme file, and also makes the capitalization in the section headers consistent.
=> Add dataset tutorial to Readme

chat/base.py, eval/lm_eval_harness.py, eval/lm_eval_harness_lora.py, generate/adapter.py, generate/adapter_v2.py, generate/base.py, generate/full.py, generate/lora.py, lit_gpt/config.py, quantize/gptq.py, scripts/convert_lit_checkpoint.py, scripts/prepare_redpajama.py, tests/test_config.py, xla/generate/adapter.py, xla/generate/base.py
@rasbt This will fix the `condense_ratio` issue
=> Introduce `Config.from_json`

xla/utils.py
Requires https://github.com/Lightning-AI/lightning/pull/18497
=> Update XLA code to use latest XLAFSDP changes

tutorials/prepare_dataset.md
This tutorial explains how users can bring their own datasets or add new datasets.
Fixes #487
=> Preparing custom datasets instructions

lit_gpt/config.py, scripts/convert_hf_checkpoint.py, scripts/download.py, tests/test_model.py, tutorials/download_falcon.md
=> Add falcon-180B checkpoint support

lit_gpt/adapter.py, lit_gpt/adapter_v2.py, lit_gpt/lora.py, lit_gpt/model.py, tests/test_model.py
This has the advantage that `forward` always returns a single tensor
=> Define the KV cache in the attention module

lit_gpt/adapter.py, lit_gpt/adapter_v2.py, lit_gpt/lora.py, lit_gpt/model.py
After #526, this is a more reliable check
=> Error check with max_seq_len in forward

lit_gpt/config.py
Ref: https://github.com/Lightning-AI/lit-gpt/issues/427
=> Add config for llama-2-7b-32k

lit_gpt/config.py, scripts/convert_hf_checkpoint.py, tests/test_convert_hf_checkpoint.py
=> Use `asdict` to save the config

lit_gpt/model.py, tests/test_model.py
=> Fix KV cache with AMP

scripts/prepare_alpaca.py, scripts/prepare_dolly.py, scripts/prepare_lima.py, tutorials/neurips_challenge_quickstart.md, tutorials/prepare_dataset.md
=> Adds the max_seq_length argument back to the dataset preparation scripts

scripts/convert_hf_checkpoint.py, tests/test_convert_hf_checkpoint.py
Fixes https://github.com/Lightning-AI/lit-gpt/issues/577
=> Revert Llama 70B loading change. Add test

lit_gpt/utils.py, tests/test_utils.py
Fixes https://github.com/Lightning-AI/lit-gpt/issues/574
=> Fix quantization import pattern

tutorials/neurips_challenge_quickstart.md
There have been some recent rule changes regarding LLM-generated contents, which is now allowed in certain cases. This PR updates the tutorial accordingly.
=> Update neurips_challenge_quickstart.md to add recent rule changes

.gitignore, tests/test_model.py
=> Add 16bit tests (xfailing)

README.md, requirements-all.txt, requirements-extra.txt, requirements.txt
This adds an optional requirements file so that users can install all requirements in one swoop.
=> Install with extra requirements

.github/workflows/cpu-tests.yml
=> Use all requirements file in CI

finetune/lora.py
For LLM training it's usually common practice to use a LR scheduler, which we haven't been doing in the past. What do you think about adding this as a hyperparameter option (defaulting to `False`).
What do you think? @carmocca @lantiga @awaelchli ?
If you think that's a good idea, we can add it to all finetuning and pretraining scripts.
=> Add LR scheduler to finetune/lora.py

README.md
Model size (number of parameters) for the most popular models is added.
=> Added model size

finetune/lora.py, generate/adapter.py, generate/adapter_v2.py, generate/base.py, generate/full.py, generate/lora.py
In certain error messages we incorrectly called it `--quantization`, but the correct flag is `--quantize`
=> Fix --quantization -> --quantize

requirements.txt, setup.py
We will have to pin to a specific commit soon again. But for now, we can pin to the latest release
=> Pin to Lightning 2.1

finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, lit_gpt/model.py, pretrain/openwebtext.py, pretrain/openwebtext_trainer.py, pretrain/redpajama.py, tests/conftest.py, tests/test_gptq.py, tests/test_model.py, tutorials/finetune_adapter.md, tutorials/finetune_full.md, tutorials/finetune_lora.md
Makes sure that our implementation supports Flash or Mem efficient attention
=> Add SDPA choice test

lit_gpt/config.py, scripts/download.py, tests/test_config.py, tests/test_tokenizer.py
=> Make HF meta data an optional field in Config

lit_gpt/config.py, tests/test_config.py
Hi there 👋 
This is an extension of #673.
Unfortunately, I've made a mistake a didn't hit “Submit review” button, so all my comments were visible only to me and thus the PR was merged too soon.
So this PR fixes a couple of issues:
1. Extends `test_from_hf_config` to a parametrized version. For instance, it pointed to an issue with new config: now we have a nested dictionary (`hf_config` inside config) so when we do a shallow copy it leads to an issue.
2. Replacement of `.copy` with `deepcopy.copy`.
3. Automatic code style fixes (of course 😊).
=> Config fixes

finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, pretrain/openwebtext.py, pretrain/redpajama.py, requirements.txt, setup.py, tests/test_adapter.py, tests/test_adapter_v2.py, tests/test_full.py, tests/test_lora.py, xla/finetune/adapter.py
Requires https://github.com/Lightning-AI/lightning/pull/18905 and https://github.com/Lightning-AI/lightning/pull/18924
=> Use throughput's batches argument

finetune/full.py, finetune/lora.py, pretrain/openwebtext.py, pretrain/redpajama.py
Fixes https://github.com/Lightning-AI/lit-gpt/issues/699
=> Do not use `inference_mode` with FSDP training scripts

requirements-all.txt
Fix to avoid the issue https://github.com/Lightning-AI/lit-gpt/issues/707
=> Pin bitsandbytes to avoid breaking change

chat/base.py, finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, generate/adapter.py, generate/adapter_v2.py, generate/base.py, generate/full.py, generate/lora.py, xla/generate/adapter.py, xla/generate/base.py
=> Fix top_k CLI type

chat/base.py, generate/base.py, tests/test_generate.py
When `temperature` is 0, we simply call `argmax`
Llama 2 does this: https://github.com/facebookresearch/llama/blob/ef351e9cd9496c579bf9f2bb036ef11bdc5ca3d2/llama/generation.py#L188-L192
=> Simplify code path when temperature is 0

.github/azure-gpu-test.yml, .github/workflows/cpu-tests.yml, pretrain/tinyllama.py, tests/conftest.py, tests/run_standalone_tests.sh, tests/test_adapter.py, tests/test_adapter_v2.py, tests/test_ci.py, tests/test_convert_lit_checkpoint.py, tests/test_gptq.py, tests/test_lora.py, tests/test_model.py, tests/test_utils.py
=> Implement test filtering

pretrain/redpajama.py
=> Handle error when no files found in data dir 

eval/lm_eval_harness.py, lit_gpt/config.py, lit_gpt/model.py, pretrain/redpajama.py, tests/conftest.py, tests/test_config.py, tests/test_lm_eval_harness.py, tutorials/evaluation.md, tutorials/finetune_lora.md, tutorials/neurips_challenge_quickstart.md
Fixes https://github.com/Lightning-AI/lit-gpt/issues/709
=> Update lm eval harness integration. Add tests

pretrain/openwebtext.py, pretrain/redpajama.py
=> Fix weight initialization for single-device pretrain/redpajama.py and pretrain/openwebtext.py

.gitignore, pretrain/tinyllama.py, requirements-all.txt, tutorials/pretrain_tinyllama.md
Switches CSVLogger for TensorBoardLogger in pretrain/tinyllama.py.
=> TensorBoardLogger as default logger in `pretrain/tinyllama.py`

pretrain/tinyllama.py
Log the learning rate in the TinyLLama pretraining script.
=> Log learning rate in pretrain script

chat/base.py, tests/test_chat.py
Hi there 👋 
This PR extends tests for `chat/base.py` to cover functionality of `main` and `decode` functions.
=> Tests for `chat/base.py`: `decode` and `main` functions

README.md, chat/base.py, lit_gpt/config.py, scripts/convert_hf_checkpoint.py, scripts/convert_lit_checkpoint.py, tutorials/download_stablelm.md
Hi there 👋 
Fixes #799 
A couple of days ago, Stability.ai introduced a new fine-tuned model and this PR adds support for it.
> StableLM Zephyr 3B is a 3 billion parameter Large Language Model (LLM), 60% smaller than 7B models, allowing accurate, and responsive output on a variety of devices without requiring high-end hardware. 
Links:
- [Announcement](https://stability.ai/news/stablelm-zephyr-3b-stability-llm)
- HF model's [page](https://huggingface.co/stabilityai/stablelm-zephyr-3b)
=> StableLM Zephyr 3B

tests/test_convert_lit_checkpoint.py, tests/test_model.py
Hi there 👋 
As discussed in #801, this PR adds tests to cover new -ish architecture in StableLM Zephyr 3B.
Test in `test_model.py` essentially checks hf -> lit conversion, so didn't add a test to `test_convert_hf_checkpoint.py`.
=> Tests for StableLM Zephyr 3B

README.md, chat/base.py, lit_gpt/config.py, tutorials/download_function_calling_llama_2.md
Hi! I added the config and prompt formatting to run the function calling llama 2 model from Trelis. Also added the corresponding tutorial
=> Add function calling llama 2 7b

generate/base.py, lit_gpt/model.py
=> Modeling fixes for heterogeneous devices

lit_gpt/model.py
Benchmark results:
```markdown
eager: 15665.457248687744us
3.9922048 GB
compiled: 15721.099376678467us
3.755603456 GB
eager: 49546.36335372925us
6.954663936 GB
compiled: 47361.955642700195us
5.981437952 GB
eager: 15694.758892059326us
4.106371072 GB
compiled: 15854.079723358154us
3.8705152 GB
eager: 19026.272296905518us
4.047395328 GB
compiled: 19472.668170928955us
3.809729024 GB
```
Code:
```python
import time
import torch
import torch.nn as nn
class LLaMAMLP(nn.Module):
def __init__(self) -> None:
super().__init__()
self.fc_1 = nn.Linear(n_embd, intermediate_size, bias=bias)
self.fc_2 = nn.Linear(n_embd, intermediate_size, bias=bias)
self.proj = nn.Linear(intermediate_size, n_embd, bias=bias)
def forward(self, x: torch.Tensor) -> torch.Tensor:
x_fc_1 = self.fc_1(x)
x_fc_2 = self.fc_2(x) …
```
=> Switch MoE implementation

tutorials/download_phi.md
This PR fixes minor formatting bugs and adds a note about input prompt tweaking when using phi2 model.
=> Update phi tutorial, add a note on input prompt tweaking

pretrain/tinyllama.py
A set of cosmetic updates to the `pretrain/tinyllama.py` from my current training experiments.
=> Updates to tinyllama pretrain script

pretrain/openwebtext_trainer.py, tests/test_openwebtext_trainer.py
=> Override `load_state_dict` for the GPT LightningModule

tutorials/finetune_lora.md, tutorials/quantize.md
Hi there 👋 
This tiny PR is to show that GitHub now [support](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) new set of markdown alerts, which adds flexibility to express additional information:
> [!NOTE]
> Useful information that users should know, even when skimming content.
> [!TIP]
> Helpful advice for doing things better or more easily.
> [!IMPORTANT]
> Key information users need to know to achieve their goal.
> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.
> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.
=> Updated GitHub markdown alerts

pretrain/tinyllama.py, tests/test_full.py
Minor updates from my current local changes.
=> Updates to the tinyllama pretrain script

README.md
As the title suggests, we can incentivize researchers to cite our repo :)
=> Add bibtex citation to README

tutorials/pretrain_tinyllama.md
Adds a link to the studio we used to reproduce TinyLlama.
=> Add reference to TinyLlama reproduction studio

scripts/download.py, tests/test_convert_lit_checkpoint.py, tests/test_model.py
Part of https://github.com/Lightning-AI/lit-gpt/issues/868
=> Pin Phi HF revision

scripts/download.py, tests/test_model.py
Fixes https://github.com/Lightning-AI/lit-gpt/issues/871
=> Pin Phi 2 HF revision

generate/sequentially.py, generate/tp.py, lit_gpt/model.py, tests/test_model.py
=> Fix initialization of RoPE using FSDP

scripts/convert_pretrained_checkpoint.py
Updates a comment about a feature in 2.2 that was reverted and won't be available.
=> Update comment in convert script

finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, pretrain/openwebtext.py, pretrain/redpajama.py, pretrain/tinyllama.py
To avoid having to rerun the same script until all values are fixed
=> Validate all args at once

finetune/adapter.py, finetune/adapter_v2.py, finetune/full.py, finetune/lora.py, pretrain/openwebtext.py, pretrain/redpajama.py, pretrain/tinyllama.py
Exposes the random seed as a configuration for the CLI. 
Fixes #944
=> Add random seed arg

config_hub/pretrain/debug.yaml, config_hub/pretrain/tinyllama.yaml, config_hub/pretrain/tinystories.yaml, pretrain/pretrain.py
Suggested in https://github.com/Lightning-AI/lit-gpt/pull/980#discussion_r1511757224
=> Rename pretrain `checkpoint_dir` to `tokenizer_dir`

config_hub/pretrain/debug.yaml, config_hub/pretrain/tinyllama.yaml, config_hub/pretrain/tinystories.yaml, lit_gpt/pretrain.py, tests/test_pretrain.py
=> Allow choosing model via name in pretraining script

scripts/download.py, tutorials/download_function_calling_llama_2.md, tutorials/download_gemma.md, tutorials/download_mistral.md, tutorials/download_phi.md, tutorials/download_stablecode.md, tutorials/download_stablelm.md, tutorials/download_tinyllama.md
Fixes https://github.com/Lightning-AI/lit-gpt/issues/1008
=> Automatically choose safetensors

README.md, litgpt/chat/base.py, tests/test_chat.py, tutorials/download_code_llama.md, tutorials/download_freewilly_2.md, tutorials/download_function_calling_llama_2.md, tutorials/download_gemma.md, tutorials/download_llama_2.md, tutorials/download_longchat.md, tutorials/download_mistral.md, tutorials/download_phi.md, tutorials/download_stablecode.md, tutorials/download_stablelm.md, tutorials/download_tinyllama.md, tutorials/download_vicuna.md, tutorials/finetune_lora.md, tutorials/inference.md
Fixes #548
Won't do `eval/` for now because it's not clear what we are going to do with it yet
=> Move `chat/` inside the package

litgpt/data/json.py, tests/data/test_json.py
Allows the JSON data module to load .jsonl files.
=> Add support for loading JSONL

litgpt/utils.py, tests/test_config_hub.py
Fixes https://github.com/Lightning-AI/litgpt/issues/1072
=> Support URLs for configs

README.md, litgpt/utils.py, tests/test_utils.py, tutorials/convert_hf_checkpoint.md, tutorials/convert_lit_models.md, tutorials/download_model_weights.md, tutorials/finetune_adapter.md, tutorials/finetune_full.md, tutorials/finetune_lora.md, tutorials/inference.md, tutorials/prepare_dataset.md, tutorials/pretrain_tinyllama.md, tutorials/quantize.md
=> Use the CLI in the tutorials

config_hub/finetune/README.md, config_hub/finetune/tiny-llama/full.yaml, config_hub/finetune/tiny-llama/qlora.yaml, tests/test_config_hub.py
Adds configuration files for TinyLlama
=> Tinyllama configs

litgpt/chat/base.py, tests/test_chat.py
=> Make chat output less verbose

litgpt/utils.py, pyproject.toml, tests/test_model.py, tests/test_utils.py, tutorials/quantize.md
updated the `quant_state` API
needs needs https://github.com/Lightning-AI/pytorch-lightning/pull/19520
=> Relax bitsandbytes requirements

tests/test_config_hub.py
Slight modification of #1134 that allows us to run the test from any directory, not just the project root.
=> Improve collection of configs in test

README.md
Fixed the first link I clicked in this repo! ;)
=> chore: fixed fine-tuning link.

litgpt/config.py, litgpt/finetune/adapter.py, litgpt/finetune/adapter_v2.py, litgpt/finetune/full.py, litgpt/finetune/lora.py, litgpt/scripts/convert_hf_checkpoint.py, litgpt/scripts/download.py, tests/test_adapter.py, tests/test_adapter_v2.py, tests/test_config_hub.py, tests/test_full.py, tests/test_lora.py, tutorials/download_model_weights.md
=> Expose `model_name` from download

tutorials/finetune.md
=> Fix link in finetune.md

extensions/xla/finetune/adapter.py, litgpt/finetune/adapter.py, litgpt/finetune/adapter_v2.py, litgpt/finetune/lora.py, tests/test_adapter.py, tests/test_adapter_v2.py, tests/test_lora.py
Afaik it should be "non-trainable" or "nontrainable" but not "non trainable".
=> Small grammar fix

litgpt/chat/base.py, litgpt/finetune/adapter.py, litgpt/finetune/adapter_v2.py, litgpt/finetune/full.py, litgpt/finetune/lora.py, litgpt/generate/adapter.py, litgpt/generate/adapter_v2.py, litgpt/generate/base.py, litgpt/generate/full.py, litgpt/generate/sequentially.py, litgpt/generate/tp.py, litgpt/scripts/merge_lora.py, litgpt/utils.py, tests/test_config_hub.py
Or else `Config.from_file(checkpoint_dir / ...)` gives a hard error
=> Check checkpoint dir before accessing it

extensions/thunder/README.md
Follow-up to https://github.com/Lightning-AI/lightning-thunder/pull/69
=> Update Thunder's GPT traces in the README

litgpt/lora.py, litgpt/scripts/merge_lora.py
Aims to fix https://github.com/Lightning-AI/litgpt/issues/1181.
This seems to go from 15.1 GB peak used RAM to 11.6 in my machine using stablelm 3b
=> Meta device and assign in `merge_lora`

extensions/thunder/unsloth/executor.py
A conversation with @rasbt made me realize that this could use `replaces=` too
=> Use `replaces=` for swiglu

config_hub/finetune/README.md, config_hub/finetune/gemma-2b/lora.yaml, config_hub/finetune/gemma-2b/qlora.yaml, config_hub/finetune/gemma-7b/lora.yaml, config_hub/finetune/gemma-7b/qlora.yaml
I reran the Gemma finetunes after @Andrei-Aksionov 's Gemma fixes. Thanks again @Andrei-Aksionov  for all the awesome contributions!
=> Updated gemma configs

litgpt/pretrain.py
Move import to the top of the file as suggested by @awaelchli  in #1136
=> Move import to top of file

tutorials/download_model_weights.md
I added an additional info box under the model list in hope that it makes this info more prominent. I think it might not hurt as it is sometimes overlooked by users.
=> Mention usage of related finetunes

README.md
Adds a nice user project to the readme
=> Add MicroLlama

README.md
it's a swiss army knife in shape of lightning bolt (luca and i jammed on the idea)
=> proposed LitGPT logo update

config_hub/finetune/README.md, config_hub/finetune/llama-3-8b/full.yaml, config_hub/finetune/llama-3-8b/lora.yaml, config_hub/finetune/llama-3-8b/qlora.yaml
Adds config files for basic instruction finetuning.
=> Add Llama3 8B instruction finetuning configs

README.md
Update README.md to include diagram
=> Update README.md to include diagram

config_hub/pretrain/debug.yaml, config_hub/pretrain/tinyllama.yaml, config_hub/pretrain/tinystories.yaml, litgpt/pretrain.py
Allows selecting the precision for pretraining.
=> Add precision arg for pretraining

litgpt/deploy/serve.py, pyproject.toml
This moves the litserve dependency to `test` and `all` like you suggested @carmocca
=> Update litserve dependency

README.md
Mixtral MoE was missing from README.md
=> Add Mixtral MoE to README

pyproject.toml
Update version to include fixes.
https://github.com/Lightning-AI/pytorch-lightning/pull/19755
=> Update Lightning version

tests/test_generate.py
Fixes https://github.com/Lightning-AI/litgpt/pull/1360/files#r1590753388
=> Fix top-p test

.github/azure-gpu-test.yml, tests/__init__.py, tests/conftest.py, tests/test_adapter.py, tests/test_adapter_v2.py, tests/test_ci.py, tests/test_convert_lit_checkpoint.py, tests/test_generate_sequentially.py, tests/test_generate_tp.py, tests/test_lora.py, tests/test_model.py, tests/test_pretrain.py, tests/test_prompts.py, tests/test_thunder_ddp.py, tests/test_thunder_fsdp.py, tests/test_thunder_pretrain.py, tests/test_unsloth_executor.py, tests/test_utils.py
=> Unskip Thunder FSDP test

tutorials/finetune.md
Fixing a weird typo: Simillar -> Similar
=> Simillar -> Similar

extensions/thunder/README.md, extensions/thunder/strategies/thunder_ddp.py, extensions/thunder/strategies/thunder_fsdp.py, tests/conftest.py, tests/test_thunder_ddp.py, tests/test_thunder_fsdp.py
Requires https://github.com/Lightning-AI/lightning-thunder/pull/45
=> Support `no_sync` with Thunder FSDP

litgpt/finetune/adapter.py, litgpt/finetune/adapter_v2.py, litgpt/finetune/lora.py
I am pretty sure that these are equivalent, so we can remove this variable here.
=> Simplify code

extensions/thunder/pretrain.py, litgpt/pretrain.py
Fixes an issue introduced when adding the OptimizerArgs
=> Fix learning rate calculation in pretrain

README.md
Help users understand which models are supported and what their respective litgpt short-names are.
=> Explain how to list all available models

pyproject.toml
Bumps the version to 0.4.0 so we can make a PyPI release.
=> Bump version for PyPI release

tutorials/developer-docs/adding-models.md
Adds a checklist guide for those who want to contribute new models to LitGPT.
=> 'Add models' docs

litgpt/config.py, litgpt/scripts/convert_hf_checkpoint.py, litgpt/scripts/download.py
@rasbt Should be fine now, I hope! :)
I also had to re-add the model configs (litgpt/config.py), as they got deleted when you force-pushed. They should be correct (Mistral v0.3 uses a larger vocab size, but aside from that, all the settings are the same as for v0.2).
Closes #1444.
=> Fix Mistral 7B v0.3 weight download

litgpt/eval/evaluate.py, tests/test_evaluate.py
Fixes a new issue in LM Eval that may have occurred due to a version bump in the `lm_eval` suite.
=> Fixes for latest lm_eval

README.md
Adds the recent Samba research paper to the project section in the README
=> Add SAMBA to project gallery

pyproject.toml
Pins NumPy version until we can investigate NumPy 2.0 support. See issue #1494
=> Pin NumPy version

litgpt/finetune/adapter.py, litgpt/finetune/adapter_v2.py, litgpt/finetune/full.py, litgpt/finetune/lora.py, litgpt/pretrain.py
Users who run LitGPT with `initial_validation` set to `False` find the "Validating ..." comment confusing. This PR updates this wording.
CC @tchaton
=> Disable "validating ..." comment if initial_validation is False

.github/ISSUE_TEMPLATE/ask-a-question.md, .github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/feature-request.md
Adds simple issue templates to better categorize the issues and collect minimal info such as the LitGPT version, which will help with debugging.
=> Add simple issue templates

tutorials/finetune.md, tutorials/pretrain.md
Add note about installing dependencies to pretraining and finetuning pages to address #1458
Fixes #1458
=> Add note about dependencies

pyproject.toml
Increases the version after the last release.
=> Bumb version

litgpt/api.py, tests/test_api.py
After this PR, you can stream outputs from the LLM API 
```python
from litgpt import LLM
llm = LLM.load("checkpoints/google/gemma-2b-it")
result = llm.generate("hi", stream=True)
for e in result:
print(e, end="", flush=True)
```
=> add `LLM.generate` with streaming

tutorials/python-api.md
Fixes a typo in the download/setup instructions and adds the streaming usage.
=> Fix and update Python API docs

pyproject.toml
Let's see if this might help with the failing tests.
=> Bump thunder

README.md
Rework readme to feature python API as main, first thing.
=> Add new python API to readme

pyproject.toml
Bumps version to next dev version after recent release.
=> Bump to 0.4.3.dev0 version

litgpt/eval/evaluate.py
This fixes an issue we had with the latest LM Eval release today.
CC @Andrei-Aksionov
=> Fix for LM Eval harness 0.4.3

pyproject.toml
Updates the version so we can make a new release that contains bugfixes we need for Monday.
=> Update to version 0.4.3 for new release

tutorials/evaluation.md
Adds a section that explains how users can evaluate a model on a custom test set.
=> Add an explanation on how to evaluate on a custom test set

pyproject.toml
Closes https://github.com/Lightning-AI/litgpt/security/dependabot/1
=> Bump lightning version

litgpt/api.py, tests/test_api.py
Adds quantization support to Python API.
(when reading one of your comments, @apaz-cli, I realized I totally forgot this)
=> Make sure quantization is used correctly

tests/test_model.py
This improves the test using a parameterized test instead of a brute for-loop (CC @Andrei-Aksionov )
=> Improve mathstral tests

litgpt/api.py, tests/test_api.py
Applies a fix that @Andrei-Aksionov made to the chat script to the Python API code as well to fix the high memory consumption issue caused by the kv-cache.
Fixes #1588 
Fixes #1582
=> Fixes an issue where the LitGPT Python API was consuming too much memory

litgpt/model.py
This would enable us to support dynamic batched inputs with KVCache. 
cc: @rasbt
=> dynamic KV Cache batching

pyproject.toml, tests/test_readme.py
Provides a quick temporary fix for #1604 so that quantization isn't broken until we have time to investigate more next week.
=> Add quantization test and revert lightning version

litgpt/generate/sequentially.py, litgpt/generate/tp.py
Hi there 👋 
`sequentially.py` and `tp.py` doesn't apply prompt-style to the user's input.
This PR fixes it.
cc @awaelchli
=> Apply prompt style for tp.py and sequentially.py

.github/workflows/cpu-tests.yml
Just trying something with the Windows tests, which recently started failing with no reason (perhaps related to the new Mistral release, or maybe not, who knows):
```
Windows fatal exception: code 0xc0000374
Thread 0x00000d9c (most recent call first):
File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\threading.py", line 324 in wait
File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\threading.py", line 607 in wait
File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\threading.py", line 1376 in run
File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\threading.py", line 1016 in _bootstrap_inner
File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\threading.py", line 973 in _bootstrap
Thread 0x000017a4 (most recent call first):
File …
```
=> Update windows cpu-tests.yml

.github/CODEOWNERS
I propose to add Sebastian Raschka as code owner.
=> Add Sebastian as code owner

litgpt/chat/base.py
Fixes an issue where the autodownload and loading in `litgpt chat` fails on the first try.
Fixes #1621
=> Fix autodownload + conversion issue

litgpt/deploy/serve.py
This adds a `--quantize` option to the `litgpt serve` CLI.
=> Add quantization support to litgpt serve

pyproject.toml
Pin litserve version until changes are made to support the latest version
=> Pin litserve version

litgpt/api.py, litgpt/generate/sequentially.py, tests/test_api.py, tutorials/python-api.md
This adds support for using multiple devices and sequential generation in the Python API. 
E.g.,
```python
llm = LLM.load(
"microsoft/phi-2",
generate_strategy="sequential",
devices=4
)
text = llm.generate("What do llamas eat?")
print(text)
```
=> Support for using large models in the Python API via sequential generation

pyproject.toml
Bumps version so we can make a release for recent bugfixes and refactor.
=> Bumb version for 0.4.9 release

litgpt/api.py, litgpt/deploy/serve.py, tests/test_serve.py
This PR adds support for multi-GPU serving to `litgpt serve`.
=> Multi-gpu serving

pyproject.toml
Bumps the version so we can push the latest additions to the PyPI package.
=> Bumb version to 0.4.10 for next release

litgpt/api.py, tests/test_api.py
Now automatically selects all available GPUs if a user selected "sequential" or "tensor_parallel" as the distribution setting in LitGPT LLM API.
=> Auto device handling in LLM API

litgpt/api.py
Fixes an issue where the kv cache didn't get expanded correctly.
=> Fix KV cache issue in LLM API

litgpt/api.py
Adds a benchmark function so we can compare performance before and after we create a PR.  CC @apaz-cli 
```python
from litgpt.api import pull_request_benchmark_util
pull_request_benchmark_util(model_name="microsoft/phi-2")
```
PyTorch version: 2.5.0.dev20240808+cu121
Device: cuda
| Metric                               | First Iteration | Iter 2-6 Mean     | Iter 2-6 Standard Dev.  |
|--------------------------------------|-----------------|-------------------|-------------------------|
| Seconds total                        | 2.30            | 1.60              | 0.03                    |
| Seconds to first token               | N/A             | N/A               | N/A                     |
| Tokens generated                     | 26.00           | 26.00             | 0.00 …
=> Add PR benchmark util for internal use

litgpt/api.py
Will add some clarity to future benchmarks as to what is being tested.
=> Added git hash to benchmark utility.

README.md, litgpt/config.py, tests/test_model.py, tutorials/download_model_weights.md
Adds the new and improved Phi 3.5 checkpoint
=> Add Microsoft Phi 3.5 checkpoint

.github/workflows/cpu-tests.yml, pyproject.toml, tests/test_model.py
this bumps us to the master branch, thunder has stabilized enough for this to be feasible.
=> bump thunder dependency to main

litgpt/data/prepare_slimpajama.py
The tokenizer instance was not created properly, also need to specify the string positional parameter explicitly.
=> Fixing the tokenizer for slimpajama data preparation

litgpt/utils.py, tests/test_readme.py, tests/test_utils.py
Ensures that the tests also work fine in Studios.
=> Improve filepath handling in unit tests

extensions/thunder/README.md
Add a warning that users shouldn't use this Readme at the moment. It would require a rewrite (as discussed with @apaz-cli )
=> Update Thunder README.md

pyproject.toml
This bumps the version so we can make a new release featuring lots of improvements plus Llama 3.2
=> Bump version to 0.4.13 for new release

pyproject.toml
Sets up the main branch after the 0.4.13 version release
=> Post 0.4.13 release set up

tutorials/finetune_lora.md
Adds a missing explanation on how to use a model after finetuning
=> Add missing explanation on how to use a finetuned model

pyproject.toml
Bumps up the Lightning package version to the latest stable release.
CC @t-vi
=> Bump lightning version to latest stable release (2.4.0)

litgpt/data/dolly.py, litgpt/finetune/adapter.py, litgpt/finetune/adapter_v2.py, litgpt/finetune/full.py, litgpt/finetune/lora.py, tests/data/test_dolly.py
To fix the [issue](https://github.com/Lightning-AI/litgpt/issues/1760) where `context` key error was thrown in Dolly dataloader.
The following changes were made in this PR.
- Update `_transform` in `dolly.py`
- Added a test for it
- Updated printing a bit
I added the following test to simulate the original issue. The code has been tests on `MacOS`.
- `tests/data/test_dolly.py::test_dolly_missing_keys`
**Previous behavior**
**After fixing**
1. I noticed that some tests related to the tokenizer are failing. Note that these are not related to my updates (CC: @rasbt ).
2. I updated the printing logs a bit. The `instruction` was being printed twice which wasn't appealing. I have also added some newline characters. I applied it to only `lora.py`. If it is desirable, it can be applied to other …
=> [fix][1760] Added fix for the missing `context` key issue in dolly!

litgpt/tokenizer.py
Fixes a discrepancy with the tokens in Llama 3.2
Fixes #1771
=> Fix Llama 3.2 tokenizer

litgpt/model.py
This cleans up the RoPE extra configs a bit since we had unaccessed variables after the rewrite.
=> Tidy up RoPE

pyproject.toml
Readies the package for the next release.
=> Bump version for 0.5.1 bugfix release

pyproject.toml
Bumps package to next version after 0.5.1 release
=> Post 0.5.1 release setup

tutorials/evaluation.md
=> Fix prompt style usage in evaluation example

litgpt/finetune/full.py, litgpt/model.py, litgpt/pretrain.py, tests/test_api.py, tests/test_chat.py, tests/test_generate.py, tests/test_generate_adapter.py
Some cleanups in the code base.
=> Housekeeping: remove unused code and fix tests

litgpt/config.py, litgpt/prompts.py, tutorials/download_model_weights.md
Adds Nvidia Llama 3.1 70B Nemotron weights
=> Add Nvidia Llama 3.1 70B Nemotron weights

pyproject.toml
Updates the pyproject.toml for the next release cycle
=> 0.5.3 post release setup

CITATION.cff
Adds a .cff file for the citation information.
=> Add cff file

README.md, litgpt/config.py, litgpt/prompts.py, tests/test_convert_lit_checkpoint.py, tests/test_model.py, tutorials/download_model_weights.md
This will complete the Qwen2.5 series (for now unless Qwen Team releases new QwQ models).
=> Add Qwen2.5 math

pyproject.toml
Bumps the version to make a new release.
Last one was ~2 month ago.
=> Bump version for 0.5.4 release

pyproject.toml
Bumps the version to 0.5.6.dev1 after the 0.5.5 package release.
=> 0.5.5 post release setup

pyproject.toml
Maybe PyPI likes that better for our own releases.
=> use thunder weekly from pypi for pypi compat

pyproject.toml
=> release 0.5.6

.azure/gpu-test-with-thunder.yml, .azure/gpu-test.yml, .github/workflows/cpu-tests.yml
This shall help with HF models to be downloaded only once...
=> ci: use HF cache

.github/workflows/cpu-tests.yml
seems that the default action does not have shared capability
=> ci: split HF caching

pyproject.toml, tests/generate/test_sequentially.py
This test seems to be failing from time to time due to internet connection issues
=> tests: make flaky test due to connection issues

.azure/gpu-test.yml, litgpt/config.py
I think that it is better to use window offset rather than sliding window types due to the complexity it introduces.
=> feat: replace sliding window type with offset

litgpt/config.py, litgpt/model.py
Gemma 3 requires different base frequencies for local and global embeddings. Will later on index into the appropriate dimension depending on which embedding is needed.
=> feat: add local base freq for rope

tests/test_readme.py
waiting only needed time not fixed 30s
=> test: flexible wait for serve start

extensions/xla/scripts/prepare_alpaca.py, litgpt/data/alpaca.py, litgpt/data/flan.py, litgpt/data/json_data.py, litgpt/data/longform.py, litgpt/data/text_files.py, litgpt/data/tinystories.py, litgpt/generate/sequentially.py, litgpt/prompts.py, litgpt/scripts/merge_lora.py, pyproject.toml, tests/data/test_lit_data.py, tests/test_api.py, tests/test_prompts.py, tests/test_utils.py
=> try pyupgrade-up py38

litgpt/config.py, tests/test_model.py
=> feat: add gemma-3-12b

README.md, tutorials/download_model_weights.md
Add gemma 3 in readme and tutorials.
=> feat: add gemma 3 in readme and tutorials

litgpt/scripts/convert_lit_checkpoint.py, tests/convert/test_lit_checkpoint.py, tests/test_adapter.py, tests/test_adapter_v2.py, tests/test_lora.py
Add additional tests for gemma 3
=> feat: add tests for gemma3

.github/workflows/cpu-tests.yml
=> ci: update guardian for PRs

extensions/xla/generate/adapter.py, litgpt/api.py, litgpt/generate/adapter.py, litgpt/generate/adapter_v2.py, litgpt/generate/base.py, litgpt/generate/full.py, litgpt/generate/sequentially.py, litgpt/generate/speculative_decoding.py, litgpt/generate/tp.py, litgpt/prompts.py, tests/data/test_base.py, tests/data/test_json.py, tests/test_prompts.py
=> Add optional sys prompt

.azure/gpu-test.yml
debugging why the tests fail so we do not need to skip it...
=> bump: update Torch to resolve failing test

.github/workflows/cpu-tests.yml
'Let''s see if this on GPU is a general issue for all Ubuntu 24.04, ref: https://github.com/Lightning-AI/litgpt/pull/2054#issuecomment-2897899616
=> ci: extend testing with `ubuntu-24.04`

pyproject.toml
Fix #2045
PR to run ci on lightning infra
=> Remove litserve version constraint

.azure/gpu-test.yml
required bump after https://github.com/Lightning-AI/pytorch-lightning/pull/20877
=> bump: testing with PT 2.7.1

.github/ISSUE_TEMPLATE/bug-report.yaml
following the structure as of TM and PL
=> update bug-report/issue with reproducing in Studio

.azure/gpu-test.yml, .github/workflows/cpu-tests.yml, pyproject.toml
enable showing the longest running tests for possible improvements
=> ci: show the longest tests for improvement

tests/ext_thunder/test_unsloth_executor.py
=> Use torch autograd integration for backward testing
